/* Generated by Nim Compiler v0.16.1 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/almynic/Nim/lib -o /home/almynic/Desktop/NimProjects/SeriesManager/nimcache/seriesManager.o /home/almynic/Desktop/NimProjects/SeriesManager/nimcache/seriesManager.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <dirent.h>
#include <setjmp.h>
#include <sys/types.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>
#include <stdio.h>
#undef linux
typedef struct TY_sM4lkSb7zS6F7OVMvW9cffQ TY_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell_1zcF9cV8XIAtbN8h5HRUB8g Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct CellSeq_Axo1XVm9aaQueTOldv8le5w CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct GcHeap_1TRH1TZMaVZTnLNcIHuNFQ GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct GcStack_7fytPA5bBsob6See21YMRA GcStack_7fytPA5bBsob6See21YMRA;
typedef struct MemRegion_x81NhDv59b8ercDZ9bi85jyg MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct SmallChunk_tXn60W2f8h3jgAYdEmy5NQ SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct LLChunk_XsENErzHIZV9bhvyJx56wGw LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct BigChunk_Rv9c70Uhp2TytkX7eH78qEg BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct IntSet_EZObFrE3NC9bIb3YMkY9crZA IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct Trunk_W0r8S0Y3UGke6T9bIUWnnuw Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct AvlNode_IaqjtwKhxLEpvDS9bct9blEw AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct GcStat_0RwLoVBHZPfUAcLczmfQAg GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct CellSet_jG87P0AI9aZtss9ccTYBIISQ CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct PageDesc_fublkgIY4LG3mT51LU2WHg PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TSafePoint TSafePoint;
typedef struct TY_UV3llMMYFckfui8YMBuUZA TY_UV3llMMYFckfui8YMBuUZA;
typedef struct TY_7q7q3E6Oj24ZNVJb9aonhAg TY_7q7q3E6Oj24ZNVJb9aonhAg;
typedef struct BaseChunk_Sdq7WpT6qAH858F5ZEdG3w BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct FreeCell_u6M5LHprqzkn9axr04yg9bGQ FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct Pcre_bGVj3RgRlNY6kwJpiYI9b3A Pcre_bGVj3RgRlNY6kwJpiYI9b3A;
typedef struct ExtraData_aRbi7557vgG4KV47nk1CWQ ExtraData_aRbi7557vgG4KV47nk1CWQ;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct  TNimType  {
NI size;
TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, TY_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct  Cell_1zcF9cV8XIAtbN8h5HRUB8g  {
NI refcount;
TNimType* typ;
};
struct  GcStack_7fytPA5bBsob6See21YMRA  {
void* bottom;
};
struct  CellSeq_Axo1XVm9aaQueTOldv8le5w  {
NI len;
NI cap;
Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* TY_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef Trunk_W0r8S0Y3UGke6T9bIUWnnuw* TY_lh2A89ahMmYg9bCmpVaplLbA[256];
struct  IntSet_EZObFrE3NC9bIb3YMkY9crZA  {
TY_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef AvlNode_IaqjtwKhxLEpvDS9bct9blEw* TY_0aOLqZchNi8nWtMTi8ND8w[2];
struct  AvlNode_IaqjtwKhxLEpvDS9bct9blEw  {
TY_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct  MemRegion_x81NhDv59b8ercDZ9bi85jyg  {
NI minLargeObj;
NI maxLargeObj;
TY_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* heapLink;
IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
};
struct  GcStat_0RwLoVBHZPfUAcLczmfQAg  {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct  CellSet_jG87P0AI9aZtss9ccTYBIISQ  {
NI counter;
NI max;
PageDesc_fublkgIY4LG3mT51LU2WHg* head;
PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct  GcHeap_1TRH1TZMaVZTnLNcIHuNFQ  {
GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
typedef NimStringDesc* TY_sMpvt1sOxOJ3LFGulnbeMQ[4];
typedef NimStringDesc* TY_DLxB9cOndPvLDyky9bY9ccM3g[7];
typedef NimStringDesc* TY_nHXaesL0DJZHyVS07ARPRA[1];
typedef NU8 RegexFlag_gA189bEOtGhLt2cCHGW4ywg_Set;
typedef NU8 PathComponent_9c1SIU9cO1wHcl09b703A9cDrg;
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} TY_KeeAOYBd84Ofsw6Y7LizaQ;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
typedef NIM_CHAR TY_dTlC27m9c9aWd5dvuePYanug[256];
struct TY_UV3llMMYFckfui8YMBuUZA {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
struct TY_7q7q3E6Oj24ZNVJb9aonhAg {
NimStringDesc* Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
};
struct  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w  {
NI prevSize;
NI size;
NI origSize;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* heapLink;
};
struct  SmallChunk_tXn60W2f8h3jgAYdEmy5NQ  {
  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct  LLChunk_XsENErzHIZV9bhvyJx56wGw  {
NI size;
NI acc;
LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct  BigChunk_Rv9c70Uhp2TytkX7eH78qEg  {
  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI TY_9a8QARi5WsUggNU9bom7kzTQ[8];
struct  Trunk_W0r8S0Y3UGke6T9bIUWnnuw  {
Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct  PageDesc_fublkgIY4LG3mT51LU2WHg  {
PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct  RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw  {
Pcre_bGVj3RgRlNY6kwJpiYI9b3A* h;
ExtraData_aRbi7557vgG4KV47nk1CWQ* e;
};
struct  FreeCell_u6M5LHprqzkn9axr04yg9bGQ  {
FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct  Pcre_bGVj3RgRlNY6kwJpiYI9b3A  {
char dummy;
};
struct  ExtraData_aRbi7557vgG4KV47nk1CWQ  {
long flags;
void* study_data;
long match_limit;
void* callout_data;
void* tables;
long match_limit_recursion;
void* mark;
void* executable_jit;
};
struct TY_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_J0OujsCJVF855gnHg567Eg_2)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(TY_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(CellSeq_Axo1XVm9aaQueTOldv8le5w* s, Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
static N_NIMCALL(void, TM_J0OujsCJVF855gnHg567Eg_3)(void);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
static N_NIMCALL(void, TM_J0OujsCJVF855gnHg567Eg_9)(void);
static N_NIMCALL(void, TM_J0OujsCJVF855gnHg567Eg_18)(void);
static N_NIMCALL(void, TM_J0OujsCJVF855gnHg567Eg_21)(void);
N_NIMCALL(RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw*, re_2TnOqvPvxix6tRYnuIeq9bw)(NimStringDesc* s, RegexFlag_gA189bEOtGhLt2cCHGW4ywg_Set flags);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_NIMCALL(void, TM_J0OujsCJVF855gnHg567Eg_23)(void);
static N_NIMCALL(void, TM_J0OujsCJVF855gnHg567Eg_25)(void);
static N_NIMCALL(void, TM_J0OujsCJVF855gnHg567Eg_27)(void);
static N_NIMCALL(void, TM_J0OujsCJVF855gnHg567Eg_29)(void);
N_NIMCALL(NimStringDesc*, removeDots_yAME5eiCXTWumJo4Fxeg8Q)(NimStringDesc* fileName);
N_NIMCALL(NimStringDesc*, nsuReplaceStr)(NimStringDesc* s, NimStringDesc* sub, NimStringDesc* by);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void, processDirectory_YsFxgeEY9c7k81HND5GwKVA)(NimStringDesc* workingDirectory);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
N_NIMCALL(NimStringDesc*, slash__lXoMhn1ZYc9cAJa9bfA61msg)(NimStringDesc* head, NimStringDesc* tail);
static N_INLINE(NIM_BOOL, dirExists_wf0Ae3eLXw0lSNEFJMV3ogseriesManager)(NimStringDesc* dir);
N_NIMCALL(NIM_BOOL, nosexistsDir)(NimStringDesc* dir);
N_NIMCALL(void, nossplitPath)(NimStringDesc* path, TY_UV3llMMYFckfui8YMBuUZA* Result);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
N_NIMCALL(PathComponent_9c1SIU9cO1wHcl09b703A9cDrg, getSymlinkFileKind_WoXOp8qmMec1P4MyA3LBKg)(NimStringDesc* path);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(void, reraiseException)(void);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_NIMCALL(void, move_data_RuqyGIgEE9cw30IzHQ1oRaQ)(NimStringDesc* fileOrDirectory, NimStringDesc* destDir);
N_NIMCALL(void, nosmoveFile)(NimStringDesc* source, NimStringDesc* dest);
N_NIMCALL(NimStringDesc*, getSeriesNameFromFile_Yt9cWKv49axGWv9cwAXa64wew)(NimStringDesc* fileName);
N_NIMCALL(NimStringDesc*, stripFileEnding_yAME5eiCXTWumJo4Fxeg8Q_2)(NimStringDesc* fileName);
N_NIMCALL(void, nossplitFile)(NimStringDesc* path, TY_7q7q3E6Oj24ZNVJb9aonhAg* Result);
N_NIMCALL(NimStringDesc*, deleteEverythingAfterEpisodePattern_Yt9cWKv49axGWv9cwAXa64wew_2)(NimStringDesc* fileName);
static N_INLINE(NIM_BOOL, contains_y7rJUCS8uxf8NYoExwh5sA_2re)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start);
static N_INLINE(NI, find_Qgadm9adOmbpTJaQImyB4SQ_2re)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start);
N_NIMCALL(NI, find_gO27BvVdKY9cNNmXqtaKGdQ)(NCSTRING buf, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start, NI bufSize);
static N_INLINE(TY_sM4lkSb7zS6F7OVMvW9cffQ*, split_Z7ZBo8kHSBAfoa09amRR7igre)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* sep);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
static N_INLINE(NI, matchLen_Qgadm9adOmbpTJaQImyB4SQre)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start);
N_NIMCALL(int, matchOrFind_lYP9aKTHndN56JtpfLZGvIg)(NCSTRING buf, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start, NI bufSize, int flags);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(void, movingFoldersToSeriesFolders_hRVxzheqtPypyf09cCOcHOg)(NimStringDesc* folderName, NimStringDesc* destFolder);
N_NIMCALL(void, movingFilesToSeriesFolders_dRPWxy9a59cccP9c9cAYHo7ypA)(NimStringDesc* fileName, NimStringDesc* destFolder);
N_NIMCALL(NimStringDesc*, removeYearSequence_wurmAF3YsTQS52r0ooQM0A)(NimStringDesc* fileName);
N_NIMCALL(NimStringDesc*, replace_XTFad3adT9ckW2xJiSYMhMw)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* sub, NimStringDesc* by);
N_NIMCALL(NimStringDesc*, removeVideoEncodingInformationFromFileName_wurmAF3YsTQS52r0ooQM0A_2)(NimStringDesc* fileName);
N_NIMCALL(NIM_BOOL, isSeriesEpisode_6t9aU2kB4FzgoQqgCkhImpQ)(NimStringDesc* fileName);
N_NIMCALL(NimStringDesc*, stripEverythingfromFileName_Yt9cWKv49axGWv9cwAXa64wew_3)(NimStringDesc* fileName);
N_NIMCALL(NIM_BOOL, isMovie_YcYvVRYugMmk6vNOnvG04g)(NimStringDesc* fileName);
N_NIMCALL(void, similarityCheckOnVariableLength_y2YHU9aZPhSGftI5Xw7jTEg)(void);
N_NIMCALL(NI, levensthein_y0rRchiR9aZQHKzZJeP8CFQ)(NimStringDesc* fileName, NimStringDesc* serieFolder);
N_NIMCALL(NI, nsuEditDistance)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, contains_jPdUhZfr9a8sH2V3ZBDljzwseriesManager)(NimStringDesc** a, NI aLen_0, NimStringDesc* item);
static N_INLINE(NI, find_9basNl9bVqn7SOf9bgUeI8TEQseriesManager)(NimStringDesc** a, NI aLen_0, NimStringDesc* item);
N_NIMCALL(NIM_BOOL, doesSeriesFolderExist_q4WqvETqd5h7W7fOAf9bFpA)(NimStringDesc* workingDirectory, NimStringDesc* fileName);
N_NIMCALL(NimStringDesc*, nimBoolToStr)(NIM_BOOL x);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_pcreInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_pcreDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_rtarraysInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_rtarraysDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_reInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_reDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, seriesManagerDatInit000)(void);
TY_sM4lkSb7zS6F7OVMvW9cffQ* dataToBeProecessed_aGKSlMaoiyeQEXicsP8HXw;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
TY_sMpvt1sOxOJ3LFGulnbeMQ fileExtensions_K9clLC6KernbjfUsLEODX1Q;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
TNimType NTI_sMpvt1sOxOJ3LFGulnbeMQ_;
TY_DLxB9cOndPvLDyky9bY9ccM3g videoEncodingFormat_dAy9cWFlcUPig52GMS3XhzA;
TNimType NTI_DLxB9cOndPvLDyky9bY9ccM3g_;
TY_nHXaesL0DJZHyVS07ARPRA seriesNameFolders_ApgA9cgSfvlp9bB9b9cZhrgltg;
TNimType NTI_nHXaesL0DJZHyVS07ARPRA_;
RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* episodePattern1_2coGGuZQmgjPi0ltcHTQ0g;
extern TNimType NTI_dkhOdInu11QXB2HnNpgmJQ_;
RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* episodePattern2_h2An9ay29cIRc09cJGyK4JTBw;
RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* episodePattern3_cM7OgiY1WNSwP9avickKvFg;
RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* episodePattern4_cyw3gVguaMr6sG0K49b6ElQ;
RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* yearPattern_h2XZ0aCURHWP8N30Rxb5YQ;
extern TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
STRING_LITERAL(TM_J0OujsCJVF855gnHg567Eg_5, ".avi", 4);
STRING_LITERAL(TM_J0OujsCJVF855gnHg567Eg_6, ".mkv", 4);
STRING_LITERAL(TM_J0OujsCJVF855gnHg567Eg_7, ".srt", 4);
STRING_LITERAL(TM_J0OujsCJVF855gnHg567Eg_8, ".mp4", 4);
NIM_CONST TY_sMpvt1sOxOJ3LFGulnbeMQ TM_J0OujsCJVF855gnHg567Eg_4 = {((NimStringDesc*) &TM_J0OujsCJVF855gnHg567Eg_5),
((NimStringDesc*) &TM_J0OujsCJVF855gnHg567Eg_6),
((NimStringDesc*) &TM_J0OujsCJVF855gnHg567Eg_7),
((NimStringDesc*) &TM_J0OujsCJVF855gnHg567Eg_8)}
;
STRING_LITERAL(TM_J0OujsCJVF855gnHg567Eg_11, "x264", 4);
STRING_LITERAL(TM_J0OujsCJVF855gnHg567Eg_12, "HDTV", 4);
STRING_LITERAL(TM_J0OujsCJVF855gnHg567Eg_13, "720p", 4);
STRING_LITERAL(TM_J0OujsCJVF855gnHg567Eg_14, "480p", 4);
STRING_LITERAL(TM_J0OujsCJVF855gnHg567Eg_15, "1080p", 5);
STRING_LITERAL(TM_J0OujsCJVF855gnHg567Eg_16, "Bluray", 6);
STRING_LITERAL(TM_J0OujsCJVF855gnHg567Eg_17, "YIFY", 4);
NIM_CONST TY_DLxB9cOndPvLDyky9bY9ccM3g TM_J0OujsCJVF855gnHg567Eg_10 = {((NimStringDesc*) &TM_J0OujsCJVF855gnHg567Eg_11),
((NimStringDesc*) &TM_J0OujsCJVF855gnHg567Eg_12),
((NimStringDesc*) &TM_J0OujsCJVF855gnHg567Eg_13),
((NimStringDesc*) &TM_J0OujsCJVF855gnHg567Eg_14),
((NimStringDesc*) &TM_J0OujsCJVF855gnHg567Eg_15),
((NimStringDesc*) &TM_J0OujsCJVF855gnHg567Eg_16),
((NimStringDesc*) &TM_J0OujsCJVF855gnHg567Eg_17)}
;
STRING_LITERAL(TM_J0OujsCJVF855gnHg567Eg_20, "", 0);
NIM_CONST TY_nHXaesL0DJZHyVS07ARPRA TM_J0OujsCJVF855gnHg567Eg_19 = {((NimStringDesc*) &TM_J0OujsCJVF855gnHg567Eg_20)}
;
STRING_LITERAL(TM_J0OujsCJVF855gnHg567Eg_22, "[a-zA-Z][0-9][0-9][a-zA-Z][0-9][0-9]", 36);
STRING_LITERAL(TM_J0OujsCJVF855gnHg567Eg_24, "[a-zA-Z]+[0-9][0-9][a-zA-Z]+[0-9]+", 34);
STRING_LITERAL(TM_J0OujsCJVF855gnHg567Eg_26, "\\d\\d\\d", 6);
STRING_LITERAL(TM_J0OujsCJVF855gnHg567Eg_28, "\\d\\dx\\d\\d", 9);
STRING_LITERAL(TM_J0OujsCJVF855gnHg567Eg_30, "\\d\\d\\d\\d", 8);
STRING_LITERAL(TM_J0OujsCJVF855gnHg567Eg_31, ".", 1);
STRING_LITERAL(TM_J0OujsCJVF855gnHg567Eg_32, " ", 1);
STRING_LITERAL(TM_J0OujsCJVF855gnHg567Eg_34, "..", 2);
STRING_LITERAL(TM_J0OujsCJVF855gnHg567Eg_36, "len(a) == L seq modified while iterating over it", 48);
STRING_LITERAL(TM_J0OujsCJVF855gnHg567Eg_44, "chicago.justice.s01e04.HDTV.x265-SVA[Prime].mkv", 47);
STRING_LITERAL(TM_J0OujsCJVF855gnHg567Eg_45, "chicago justice", 15);
static N_NIMCALL(void, TM_J0OujsCJVF855gnHg567Eg_2)(void) {
	nimGCvisit((void*)dataToBeProecessed_aGKSlMaoiyeQEXicsP8HXw, 0);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim")
	result = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(138, "gc.nim");
	result = ((Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim")
	nimln_(216, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim")
	nimln_(270, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(272, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(273, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}
static N_NIMCALL(void, TM_J0OujsCJVF855gnHg567Eg_3)(void) {
	NI T1_;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < 4; T1_++) {
	nimGCvisit((void*)fileExtensions_K9clLC6KernbjfUsLEODX1Q[T1_], 0);
	}
}
static N_NIMCALL(void, TM_J0OujsCJVF855gnHg567Eg_9)(void) {
	NI T1_;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < 7; T1_++) {
	nimGCvisit((void*)videoEncodingFormat_dAy9cWFlcUPig52GMS3XhzA[T1_], 0);
	}
}
static N_NIMCALL(void, TM_J0OujsCJVF855gnHg567Eg_18)(void) {
	NI T1_;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < 1; T1_++) {
	nimGCvisit((void*)seriesNameFolders_ApgA9cgSfvlp9bB9b9cZhrgltg[T1_], 0);
	}
}
static N_NIMCALL(void, TM_J0OujsCJVF855gnHg567Eg_21)(void) {
	nimGCvisit((void*)episodePattern1_2coGGuZQmgjPi0ltcHTQ0g, 0);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim")
	nimln_(288, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(347, "system.nim");
		nimln_(288, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(289, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(290, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(291, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(347, "system.nim");
		nimln_(291, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(292, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(293, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(294, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(295, "gc.nim");
	(*dest) = src;
	popFrame();
}
static N_NIMCALL(void, TM_J0OujsCJVF855gnHg567Eg_23)(void) {
	nimGCvisit((void*)episodePattern2_h2An9ay29cIRc09cJGyK4JTBw, 0);
}
static N_NIMCALL(void, TM_J0OujsCJVF855gnHg567Eg_25)(void) {
	nimGCvisit((void*)episodePattern3_cM7OgiY1WNSwP9avickKvFg, 0);
}
static N_NIMCALL(void, TM_J0OujsCJVF855gnHg567Eg_27)(void) {
	nimGCvisit((void*)episodePattern4_cyw3gVguaMr6sG0K49b6ElQ, 0);
}
static N_NIMCALL(void, TM_J0OujsCJVF855gnHg567Eg_29)(void) {
	nimGCvisit((void*)yearPattern_h2XZ0aCURHWP8N30Rxb5YQ, 0);
}

N_NIMCALL(NimStringDesc*, removeDots_yAME5eiCXTWumJo4Fxeg8Q)(NimStringDesc* fileName) {
	NimStringDesc* result;
	NimStringDesc* fileNameWithoutDots;
	nimfr_("removeDots", "seriesManager.nim")
{	result = (NimStringDesc*)0;
	nimln_(40, "seriesManager.nim");
	fileNameWithoutDots = nsuReplaceStr(fileName, ((NimStringDesc*) &TM_J0OujsCJVF855gnHg567Eg_31), ((NimStringDesc*) &TM_J0OujsCJVF855gnHg567Eg_32));
	nimln_(41, "seriesManager.nim");
	result = copyString(fileNameWithoutDots);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler_rqLlY5bs9atDw2OXYqJEn5g;
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = s;
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NIM_BOOL, dirExists_wf0Ae3eLXw0lSNEFJMV3ogseriesManager)(NimStringDesc* dir) {
	NIM_BOOL result;
	nimfr_("dirExists", "os.nim")
	result = (NIM_BOOL)0;
	nimln_(252, "os.nim");
	nimln_(253, "os.nim");
	result = nosexistsDir(dir);
	popFrame();
	return result;
}

static N_INLINE(void, popSafePoint)(void) {
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = (*excHandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(void, processDirectory_YsFxgeEY9c7k81HND5GwKVA)(NimStringDesc* workingDirectory) {
	nimfr_("processDirectory", "seriesManager.nim")
	{
		PathComponent_9c1SIU9cO1wHcl09b703A9cDrg kind;
		NimStringDesc* path;
		DIR* d;
		kind = (PathComponent_9c1SIU9cO1wHcl09b703A9cDrg)0;
		path = (NimStringDesc*)0;
		nimln_(974, "os.nim");
		d = opendir(workingDirectory->data);
		nimln_(975, "os.nim");
		{
			TSafePoint TM_J0OujsCJVF855gnHg567Eg_33;
			nimln_(347, "system.nim");
			nimln_(975, "os.nim");
			if (!!((d == NIM_NIL))) goto LA4_;
			nimln_(976, "os.nim");
			pushSafePoint(&TM_J0OujsCJVF855gnHg567Eg_33);
			TM_J0OujsCJVF855gnHg567Eg_33.status = setjmp(TM_J0OujsCJVF855gnHg567Eg_33.context);
			if (TM_J0OujsCJVF855gnHg567Eg_33.status == 0) {
				{
					nimln_(977, "os.nim");
					while (1) {
						{
							struct dirent* x;
							NimStringDesc* volatile y;
							nimln_(978, "os.nim");
							x = readdir(d);
							nimln_(979, "os.nim");
							{
								if (!(x == NIM_NIL)) goto LA12_;
								goto LA7;
							}
							LA12_: ;
							nimln_(980, "os.nim");
							y = cstrToNimstr(((NCSTRING) ((*x).d_name)));
							nimln_(981, "os.nim");
							{
								NIM_BOOL T16_;
								struct stat s;
								PathComponent_9c1SIU9cO1wHcl09b703A9cDrg volatile k;
								TY_UV3llMMYFckfui8YMBuUZA T58_;
								NimStringDesc* T59_;
								T16_ = (NIM_BOOL)0;
								nimln_(347, "system.nim");
								nimln_(981, "os.nim");
								T16_ = !(eqStrings(y, ((NimStringDesc*) &TM_J0OujsCJVF855gnHg567Eg_31)));
								if (!(T16_)) goto LA17_;
								nimln_(347, "system.nim");
								nimln_(981, "os.nim");
								T16_ = !(eqStrings(y, ((NimStringDesc*) &TM_J0OujsCJVF855gnHg567Eg_34)));
								LA17_: ;
								if (!T16_) goto LA18_;
								memset((void*)(&s), 0, sizeof(s));
								nimln_(983, "os.nim");
								{
									if (!NIM_TRUE) goto LA22_;
									nimln_(984, "os.nim");
									y = slash__lXoMhn1ZYc9cAJa9bfA61msg(workingDirectory, y);
								}
								LA22_: ;
								nimln_(985, "os.nim");
								k = ((PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 0);
								nimln_(988, "os.nim");
								{
									TY_UV3llMMYFckfui8YMBuUZA T42_;
									NimStringDesc* T43_;
									nimln_(347, "system.nim");
									nimln_(988, "os.nim");
									if (!!(((*x).d_type == ((NI8) 0)))) goto LA26_;
									nimln_(989, "os.nim");
									{
										if (!((*x).d_type == ((NI8) 4))) goto LA30_;
										k = ((PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 2);
									}
									LA30_: ;
									nimln_(990, "os.nim");
									{
										if (!((*x).d_type == ((NI8) 10))) goto LA34_;
										nimln_(991, "os.nim");
										{
											NIM_BOOL T38_;
											T38_ = (NIM_BOOL)0;
											T38_ = dirExists_wf0Ae3eLXw0lSNEFJMV3ogseriesManager(y);
											if (!T38_) goto LA39_;
											k = ((PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 3);
										}
										goto LA36_;
										LA39_: ;
										{
											nimln_(992, "os.nim");
											k = ((PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 1);
										}
										LA36_: ;
									}
									LA34_: ;
									nimln_(993, "os.nim");
									kind = k;
									path = y;
									nimln_(45, "seriesManager.nim");
									memset((void*)(&T42_), 0, sizeof(T42_));
									nossplitPath(path, (&T42_));
									dataToBeProecessed_aGKSlMaoiyeQEXicsP8HXw = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&(dataToBeProecessed_aGKSlMaoiyeQEXicsP8HXw)->Sup, sizeof(NimStringDesc*));
									T43_ = (NimStringDesc*)0;
									T43_ = dataToBeProecessed_aGKSlMaoiyeQEXicsP8HXw->data[dataToBeProecessed_aGKSlMaoiyeQEXicsP8HXw->Sup.len]; dataToBeProecessed_aGKSlMaoiyeQEXicsP8HXw->data[dataToBeProecessed_aGKSlMaoiyeQEXicsP8HXw->Sup.len] = copyStringRC1(T42_.Field1);
									if (T43_) nimGCunrefNoCycle(T43_);
									++dataToBeProecessed_aGKSlMaoiyeQEXicsP8HXw->Sup.len;
									nimln_(994, "os.nim");
									goto LA9;
								}
								LA26_: ;
								nimln_(996, "os.nim");
								{
									int T46_;
									T46_ = (int)0;
									T46_ = lstat(y->data, (&s));
									if (!(T46_ < ((NI32) 0))) goto LA47_;
									goto LA7;
								}
								LA47_: ;
								nimln_(997, "os.nim");
								{
									NIM_BOOL T51_;
									T51_ = (NIM_BOOL)0;
									T51_ = S_ISDIR(s.st_mode);
									if (!T51_) goto LA52_;
									nimln_(998, "os.nim");
									k = ((PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 2);
								}
								goto LA49_;
								LA52_: ;
								{
									NIM_BOOL T55_;
									nimln_(999, "os.nim");
									T55_ = (NIM_BOOL)0;
									T55_ = S_ISLNK(s.st_mode);
									if (!T55_) goto LA56_;
									nimln_(1000, "os.nim");
									k = getSymlinkFileKind_WoXOp8qmMec1P4MyA3LBKg(y);
								}
								goto LA49_;
								LA56_: ;
								LA49_: ;
								nimln_(1001, "os.nim");
								kind = k;
								path = y;
								nimln_(45, "seriesManager.nim");
								memset((void*)(&T58_), 0, sizeof(T58_));
								nossplitPath(path, (&T58_));
								dataToBeProecessed_aGKSlMaoiyeQEXicsP8HXw = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&(dataToBeProecessed_aGKSlMaoiyeQEXicsP8HXw)->Sup, sizeof(NimStringDesc*));
								T59_ = (NimStringDesc*)0;
								T59_ = dataToBeProecessed_aGKSlMaoiyeQEXicsP8HXw->data[dataToBeProecessed_aGKSlMaoiyeQEXicsP8HXw->Sup.len]; dataToBeProecessed_aGKSlMaoiyeQEXicsP8HXw->data[dataToBeProecessed_aGKSlMaoiyeQEXicsP8HXw->Sup.len] = copyStringRC1(T58_.Field1);
								if (T59_) nimGCunrefNoCycle(T59_);
								++dataToBeProecessed_aGKSlMaoiyeQEXicsP8HXw->Sup.len;
							}
							LA18_: ;
						} LA9: ;
					}
				} LA7: ;
				popSafePoint();
			}
			else {
				popSafePoint();
				setFrame((TFrame*)&FR_);
			}
			{
				int T62_;
				nimln_(976, "os.nim");
				T62_ = (int)0;
				T62_ = closedir(d);
			}
			if (TM_J0OujsCJVF855gnHg567Eg_33.status != 0) reraiseException();
		}
		LA4_: ;
	}
	{
		NimStringDesc* data;
		NI i;
		NI L;
		data = (NimStringDesc*)0;
		nimln_(3544, "system.nim");
		i = ((NI) 0);
		nimln_(3545, "system.nim");
		L = (dataToBeProecessed_aGKSlMaoiyeQEXicsP8HXw ? dataToBeProecessed_aGKSlMaoiyeQEXicsP8HXw->Sup.len : 0);
		{
			nimln_(3546, "system.nim");
			while (1) {
				NimStringDesc* series_name;
				NI TM_J0OujsCJVF855gnHg567Eg_35;
				if (!(i < L)) goto LA65;
				nimln_(3547, "system.nim");
				if ((NU)(i) >= (NU)(dataToBeProecessed_aGKSlMaoiyeQEXicsP8HXw->Sup.len)) raiseIndexError();
				data = dataToBeProecessed_aGKSlMaoiyeQEXicsP8HXw->data[i];
				nimln_(47, "seriesManager.nim");
				series_name = getSeriesNameFromFile_Yt9cWKv49axGWv9cwAXa64wew(data);
				nimln_(3548, "system.nim");
				TM_J0OujsCJVF855gnHg567Eg_35 = addInt(i, ((NI) 1));
				i = (NI)(TM_J0OujsCJVF855gnHg567Eg_35);
				nimln_(3549, "system.nim");
				{
					if (!!(((dataToBeProecessed_aGKSlMaoiyeQEXicsP8HXw ? dataToBeProecessed_aGKSlMaoiyeQEXicsP8HXw->Sup.len : 0) == L))) goto LA68_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_J0OujsCJVF855gnHg567Eg_36));
				}
				LA68_: ;
			} LA65: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, move_data_RuqyGIgEE9cw30IzHQ1oRaQ)(NimStringDesc* fileOrDirectory, NimStringDesc* destDir) {
	nimfr_("move_data", "seriesManager.nim")
	nimln_(54, "seriesManager.nim");
	nosmoveFile(fileOrDirectory, destDir);
	popFrame();
}

N_NIMCALL(NimStringDesc*, getSeriesNameFromFile_Yt9cWKv49axGWv9cwAXa64wew)(NimStringDesc* fileName) {
	NimStringDesc* result;
	NimStringDesc* fileNameStripEverything;
	NimStringDesc* T1_;
	nimfr_("getSeriesNameFromFile", "seriesManager.nim")
{	result = (NimStringDesc*)0;
	nimln_(62, "seriesManager.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = stripEverythingfromFileName_Yt9cWKv49axGWv9cwAXa64wew_3(fileName);
	fileNameStripEverything = deleteEverythingAfterEpisodePattern_Yt9cWKv49axGWv9cwAXa64wew_2(T1_);
	nimln_(63, "seriesManager.nim");
	result = copyString(fileNameStripEverything);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, stripFileEnding_yAME5eiCXTWumJo4Fxeg8Q_2)(NimStringDesc* fileName) {
	NimStringDesc* result;
	TY_7q7q3E6Oj24ZNVJb9aonhAg T1_;
	NimStringDesc* dir;
	NimStringDesc* name;
	NimStringDesc* ext;
	NimStringDesc* stripFileEnding;
	nimfr_("stripFileEnding", "seriesManager.nim")
{	result = (NimStringDesc*)0;
	nimln_(69, "seriesManager.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	nossplitFile(fileName, (&T1_));
	dir = (NimStringDesc*)0;
	dir = copyString(T1_.Field0);
	name = (NimStringDesc*)0;
	name = copyString(T1_.Field1);
	ext = (NimStringDesc*)0;
	ext = copyString(T1_.Field2);
	nimln_(70, "seriesManager.nim");
	stripFileEnding = nsuReplaceStr(fileName, ext, ((NimStringDesc*) &TM_J0OujsCJVF855gnHg567Eg_20));
	nimln_(71, "seriesManager.nim");
	result = copyString(stripFileEnding);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, find_Qgadm9adOmbpTJaQImyB4SQ_2re)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start) {
	NI result;
	nimfr_("find", "re.nim")
	result = (NI)0;
	nimln_(326, "re.nim");
	result = find_gO27BvVdKY9cNNmXqtaKGdQ(s->data, pattern, start, (s ? s->Sup.len : 0));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, contains_y7rJUCS8uxf8NYoExwh5sA_2re)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("contains", "re.nim")
{	result = (NIM_BOOL)0;
	nimln_(403, "re.nim");
	T1_ = (NI)0;
	T1_ = find_Qgadm9adOmbpTJaQImyB4SQ_2re(s, pattern, start);
	result = (((NI) 0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, matchLen_Qgadm9adOmbpTJaQImyB4SQre)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start) {
	NI result;
	int T1_;
	nimfr_("matchLen", "re.nim")
	result = (NI)0;
	nimln_(241, "re.nim");
	T1_ = (int)0;
	T1_ = matchOrFind_lYP9aKTHndN56JtpfLZGvIg(s->data, pattern, ((NI) (((int)chckRange(start, ((int) (-2147483647 -1)), ((int) 2147483647))))), ((NI) (((int)chckRange((s ? s->Sup.len : 0), ((int) (-2147483647 -1)), ((int) 2147483647))))), ((int) 16));
	result = ((NI) (T1_));
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(TY_sM4lkSb7zS6F7OVMvW9cffQ*, split_Z7ZBo8kHSBAfoa09amRR7igre)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* sep) {
	TY_sM4lkSb7zS6F7OVMvW9cffQ* result;
	nimfr_("split", "re.nim")
	result = (TY_sM4lkSb7zS6F7OVMvW9cffQ*)0;
	nimln_(2459, "system.nim");
	result = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) newSeq((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
	{
		NimStringDesc* x;
		NI first;
		NI last;
		x = (NimStringDesc*)0;
		nimln_(521, "re.nim");
		first = ((NI) -1);
		nimln_(522, "re.nim");
		last = ((NI) -1);
		{
			nimln_(523, "re.nim");
			while (1) {
				NI x_2;
				if (!(last < (s ? s->Sup.len : 0))) goto LA3;
				nimln_(524, "re.nim");
				x_2 = matchLen_Qgadm9adOmbpTJaQImyB4SQre(s, sep, last);
				nimln_(525, "re.nim");
				{
					NI TM_J0OujsCJVF855gnHg567Eg_37;
					if (!(((NI) 0) < x_2)) goto LA6_;
					TM_J0OujsCJVF855gnHg567Eg_37 = addInt(last, x_2);
					last = (NI)(TM_J0OujsCJVF855gnHg567Eg_37);
				}
				LA6_: ;
				nimln_(526, "re.nim");
				first = last;
				nimln_(527, "re.nim");
				{
					NI TM_J0OujsCJVF855gnHg567Eg_38;
					if (!(x_2 == ((NI) 0))) goto LA10_;
					TM_J0OujsCJVF855gnHg567Eg_38 = addInt(last, ((NI) 1));
					last = (NI)(TM_J0OujsCJVF855gnHg567Eg_38);
				}
				LA10_: ;
				{
					nimln_(528, "re.nim");
					while (1) {
						NI TM_J0OujsCJVF855gnHg567Eg_39;
						if (!(last < (s ? s->Sup.len : 0))) goto LA13;
						nimln_(529, "re.nim");
						x_2 = matchLen_Qgadm9adOmbpTJaQImyB4SQre(s, sep, last);
						nimln_(530, "re.nim");
						{
							if (!(((NI) 0) <= x_2)) goto LA16_;
							goto LA12;
						}
						LA16_: ;
						nimln_(531, "re.nim");
						TM_J0OujsCJVF855gnHg567Eg_39 = addInt(last, ((NI) 1));
						last = (NI)(TM_J0OujsCJVF855gnHg567Eg_39);
					} LA13: ;
				} LA12: ;
				nimln_(532, "re.nim");
				{
					NI TM_J0OujsCJVF855gnHg567Eg_40;
					NimStringDesc* T22_;
					if (!(first <= last)) goto LA20_;
					nimln_(533, "re.nim");
					TM_J0OujsCJVF855gnHg567Eg_40 = subInt(last, ((NI) 1));
					x = copyStrLast(s, first, (NI)(TM_J0OujsCJVF855gnHg567Eg_40));
					nimln_(2460, "system.nim");
					result = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&(result)->Sup, sizeof(NimStringDesc*));
					T22_ = (NimStringDesc*)0;
					T22_ = result->data[result->Sup.len]; result->data[result->Sup.len] = copyStringRC1(x);
					if (T22_) nimGCunrefNoCycle(T22_);
					++result->Sup.len;
				}
				LA20_: ;
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, deleteEverythingAfterEpisodePattern_Yt9cWKv49axGWv9cwAXa64wew_2)(NimStringDesc* fileName) {
	NimStringDesc* result;
	NimStringDesc* fileName_2;
	nimfr_("deleteEverythingAfterEpisodePattern", "seriesManager.nim")
{	result = (NimStringDesc*)0;
	nimln_(74, "seriesManager.nim");
	fileName_2 = copyString(fileName);
	nimln_(75, "seriesManager.nim");
	{
		NIM_BOOL T3_;
		TY_sM4lkSb7zS6F7OVMvW9cffQ* splitted;
		T3_ = (NIM_BOOL)0;
		T3_ = contains_y7rJUCS8uxf8NYoExwh5sA_2re(fileName_2, episodePattern1_2coGGuZQmgjPi0ltcHTQ0g, ((NI) 0));
		if (!T3_) goto LA4_;
		nimln_(76, "seriesManager.nim");
		splitted = split_Z7ZBo8kHSBAfoa09amRR7igre(fileName_2, episodePattern1_2coGGuZQmgjPi0ltcHTQ0g);
		nimln_(77, "seriesManager.nim");
		if ((NU)(((NI) 0)) >= (NU)(splitted->Sup.len)) raiseIndexError();
		fileName_2 = copyString(splitted->data[((NI) 0)]);
	}
	LA4_: ;
	nimln_(78, "seriesManager.nim");
	result = copyString(fileName_2);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(void, movingFoldersToSeriesFolders_hRVxzheqtPypyf09cCOcHOg)(NimStringDesc* folderName, NimStringDesc* destFolder) {
	nimfr_("movingFoldersToSeriesFolders", "seriesManager.nim")
	nimln_(81, "seriesManager.nim");
	printf("%s\012", ((NimStringDesc*) &TM_J0OujsCJVF855gnHg567Eg_20)? (((NimStringDesc*) &TM_J0OujsCJVF855gnHg567Eg_20))->data:"nil");
	fflush(stdout);
	popFrame();
}

N_NIMCALL(void, movingFilesToSeriesFolders_dRPWxy9a59cccP9c9cAYHo7ypA)(NimStringDesc* fileName, NimStringDesc* destFolder) {
	nimfr_("movingFilesToSeriesFolders", "seriesManager.nim")
	nimln_(83, "seriesManager.nim");
	printf("%s\012", ((NimStringDesc*) &TM_J0OujsCJVF855gnHg567Eg_20)? (((NimStringDesc*) &TM_J0OujsCJVF855gnHg567Eg_20))->data:"nil");
	fflush(stdout);
	popFrame();
}

N_NIMCALL(NimStringDesc*, removeYearSequence_wurmAF3YsTQS52r0ooQM0A)(NimStringDesc* fileName) {
	NimStringDesc* result;
	nimfr_("removeYearSequence", "seriesManager.nim")
{	result = (NimStringDesc*)0;
	nimln_(86, "seriesManager.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = contains_y7rJUCS8uxf8NYoExwh5sA_2re(fileName, yearPattern_h2XZ0aCURHWP8N30Rxb5YQ, ((NI) 0));
		if (!T3_) goto LA4_;
		nimln_(87, "seriesManager.nim");
		result = replace_XTFad3adT9ckW2xJiSYMhMw(fileName, yearPattern_h2XZ0aCURHWP8N30Rxb5YQ, ((NimStringDesc*) &TM_J0OujsCJVF855gnHg567Eg_32));
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(88, "seriesManager.nim");
	result = copyString(fileName);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, removeVideoEncodingInformationFromFileName_wurmAF3YsTQS52r0ooQM0A_2)(NimStringDesc* fileName) {
	NimStringDesc* result;
	NimStringDesc* fileNameWithoutEncoding;
	nimfr_("removeVideoEncodingInformationFromFileName", "seriesManager.nim")
{	result = (NimStringDesc*)0;
	nimln_(91, "seriesManager.nim");
	fileNameWithoutEncoding = copyString(fileName);
	{
		NimStringDesc* encoding;
		NI i;
		encoding = (NimStringDesc*)0;
		nimln_(2030, "system.nim");
		i = ((NI) 0);
		nimln_(2031, "system.nim");
		{
			if (!(((NI) (i)) <= ((NI) 6))) goto LA4_;
			{
				nimln_(2032, "system.nim");
				while (1) {
					NI TM_J0OujsCJVF855gnHg567Eg_41;
					nimln_(2033, "system.nim");
					encoding = copyString(videoEncodingFormat_dAy9cWFlcUPig52GMS3XhzA[(i)- 0]);
					nimln_(93, "seriesManager.nim");
					{
						RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* T10_;
						NIM_BOOL T11_;
						RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* T14_;
						T10_ = (RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw*)0;
						T10_ = re_2TnOqvPvxix6tRYnuIeq9bw(encoding, 24);
						T11_ = (NIM_BOOL)0;
						T11_ = contains_y7rJUCS8uxf8NYoExwh5sA_2re(fileName, T10_, ((NI) 0));
						if (!T11_) goto LA12_;
						nimln_(94, "seriesManager.nim");
						T14_ = (RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw*)0;
						T14_ = re_2TnOqvPvxix6tRYnuIeq9bw(encoding, 24);
						fileNameWithoutEncoding = replace_XTFad3adT9ckW2xJiSYMhMw(fileNameWithoutEncoding, T14_, ((NimStringDesc*) &TM_J0OujsCJVF855gnHg567Eg_20));
					}
					LA12_: ;
					nimln_(2034, "system.nim");
					{
						if (!(((NI) 6) <= ((NI) (i)))) goto LA17_;
						goto LA6;
					}
					LA17_: ;
					nimln_(2035, "system.nim");
					TM_J0OujsCJVF855gnHg567Eg_41 = addInt(i, ((NI) 1));
					if (TM_J0OujsCJVF855gnHg567Eg_41 < 0 || TM_J0OujsCJVF855gnHg567Eg_41 > 6) raiseOverflow();
					i = (NI)(TM_J0OujsCJVF855gnHg567Eg_41);
				}
			} LA6: ;
		}
		LA4_: ;
	}
	nimln_(95, "seriesManager.nim");
	result = copyString(fileNameWithoutEncoding);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, isSeriesEpisode_6t9aU2kB4FzgoQqgCkhImpQ)(NimStringDesc* fileName) {
	NIM_BOOL result;
	nimfr_("isSeriesEpisode", "seriesManager.nim")
{	result = (NIM_BOOL)0;
	nimln_(98, "seriesManager.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = contains_y7rJUCS8uxf8NYoExwh5sA_2re(fileName, episodePattern1_2coGGuZQmgjPi0ltcHTQ0g, ((NI) 0));
		if (!T3_) goto LA4_;
		nimln_(100, "seriesManager.nim");
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	goto LA1_;
	LA4_: ;
	{
		NIM_BOOL T7_;
		nimln_(101, "seriesManager.nim");
		T7_ = (NIM_BOOL)0;
		T7_ = contains_y7rJUCS8uxf8NYoExwh5sA_2re(fileName, episodePattern2_h2An9ay29cIRc09cJGyK4JTBw, ((NI) 0));
		if (!T7_) goto LA8_;
		nimln_(103, "seriesManager.nim");
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	goto LA1_;
	LA8_: ;
	{
		NIM_BOOL T11_;
		nimln_(104, "seriesManager.nim");
		T11_ = (NIM_BOOL)0;
		T11_ = contains_y7rJUCS8uxf8NYoExwh5sA_2re(fileName, episodePattern3_cM7OgiY1WNSwP9avickKvFg, ((NI) 0));
		if (!T11_) goto LA12_;
		nimln_(106, "seriesManager.nim");
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	goto LA1_;
	LA12_: ;
	{
		NIM_BOOL T15_;
		nimln_(107, "seriesManager.nim");
		T15_ = (NIM_BOOL)0;
		T15_ = contains_y7rJUCS8uxf8NYoExwh5sA_2re(fileName, episodePattern4_cyw3gVguaMr6sG0K49b6ElQ, ((NI) 0));
		if (!T15_) goto LA16_;
		nimln_(109, "seriesManager.nim");
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	goto LA1_;
	LA16_: ;
	{
		nimln_(111, "seriesManager.nim");
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, stripEverythingfromFileName_Yt9cWKv49axGWv9cwAXa64wew_3)(NimStringDesc* fileName) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	NimStringDesc* T3_;
	NimStringDesc* T4_;
	nimfr_("stripEverythingfromFileName", "seriesManager.nim")
{	result = (NimStringDesc*)0;
	nimln_(114, "seriesManager.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = removeYearSequence_wurmAF3YsTQS52r0ooQM0A(fileName);
	T2_ = (NimStringDesc*)0;
	T2_ = stripFileEnding_yAME5eiCXTWumJo4Fxeg8Q_2(T1_);
	T3_ = (NimStringDesc*)0;
	T3_ = removeVideoEncodingInformationFromFileName_wurmAF3YsTQS52r0ooQM0A_2(T2_);
	T4_ = (NimStringDesc*)0;
	T4_ = removeDots_yAME5eiCXTWumJo4Fxeg8Q(T3_);
	result = deleteEverythingAfterEpisodePattern_Yt9cWKv49axGWv9cwAXa64wew_2(T4_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, isMovie_YcYvVRYugMmk6vNOnvG04g)(NimStringDesc* fileName) {
	NIM_BOOL result;
	NimStringDesc* movieTitle;
	nimfr_("isMovie", "seriesManager.nim")
{	result = (NIM_BOOL)0;
	nimln_(117, "seriesManager.nim");
	movieTitle = stripEverythingfromFileName_Yt9cWKv49axGWv9cwAXa64wew_3(fileName);
	nimln_(118, "seriesManager.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isSeriesEpisode_6t9aU2kB4FzgoQqgCkhImpQ(movieTitle);
		if (!!(T3_)) goto LA4_;
		nimln_(119, "seriesManager.nim");
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	goto LA1_;
	LA4_: ;
	{
		nimln_(121, "seriesManager.nim");
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(void, similarityCheckOnVariableLength_y2YHU9aZPhSGftI5Xw7jTEg)(void) {
	nimfr_("similarityCheckOnVariableLength", "seriesManager.nim")
	nimln_(124, "seriesManager.nim");
	printf("%s\012", ((NimStringDesc*) &TM_J0OujsCJVF855gnHg567Eg_20)? (((NimStringDesc*) &TM_J0OujsCJVF855gnHg567Eg_20))->data:"nil");
	fflush(stdout);
	popFrame();
}

N_NIMCALL(NI, levensthein_y0rRchiR9aZQHKzZJeP8CFQ)(NimStringDesc* fileName, NimStringDesc* serieFolder) {
	NI result;
	NI levenshteinDistance;
	nimfr_("levensthein", "seriesManager.nim")
{	result = (NI)0;
	nimln_(127, "seriesManager.nim");
	levenshteinDistance = nsuEditDistance(fileName, serieFolder);
	nimln_(128, "seriesManager.nim");
	result = levenshteinDistance;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, find_9basNl9bVqn7SOf9bgUeI8TEQseriesManager)(NimStringDesc** a, NI aLen_0, NimStringDesc* item) {
	NI result;
	nimfr_("find", "system.nim")
{	result = (NI)0;
	{
		NimStringDesc* i;
		NI i_2;
		i = (NimStringDesc*)0;
		nimln_(2016, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(2017, "system.nim");
			while (1) {
				NI TM_J0OujsCJVF855gnHg567Eg_42;
				NI TM_J0OujsCJVF855gnHg567Eg_43;
				if (!(i_2 < aLen_0)) goto LA3;
				nimln_(2018, "system.nim");
				if ((NU)(i_2) >= (NU)(aLen_0)) raiseIndexError();
				i = a[i_2];
				nimln_(2250, "system.nim");
				{
					if (!eqStrings(i, item)) goto LA6_;
					goto BeforeRet_;
				}
				LA6_: ;
				nimln_(2251, "system.nim");
				TM_J0OujsCJVF855gnHg567Eg_42 = addInt(result, ((NI) 1));
				result = (NI)(TM_J0OujsCJVF855gnHg567Eg_42);
				nimln_(2019, "system.nim");
				TM_J0OujsCJVF855gnHg567Eg_43 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_J0OujsCJVF855gnHg567Eg_43);
			} LA3: ;
		}
	}
	nimln_(2252, "system.nim");
	result = ((NI) -1);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, contains_jPdUhZfr9a8sH2V3ZBDljzwseriesManager)(NimStringDesc** a, NI aLen_0, NimStringDesc* item) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("contains", "system.nim")
{	result = (NIM_BOOL)0;
	nimln_(2257, "system.nim");
	T1_ = (NI)0;
	T1_ = find_9basNl9bVqn7SOf9bgUeI8TEQseriesManager(a, aLen_0, item);
	result = (((NI) 0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, doesSeriesFolderExist_q4WqvETqd5h7W7fOAf9bFpA)(NimStringDesc* workingDirectory, NimStringDesc* fileName) {
	NIM_BOOL result;
	nimfr_("doesSeriesFolderExist", "seriesManager.nim")
{	result = (NIM_BOOL)0;
	nimln_(131, "seriesManager.nim");
	{
		NimStringDesc* T3_;
		NIM_BOOL T4_;
		T3_ = (NimStringDesc*)0;
		T3_ = getSeriesNameFromFile_Yt9cWKv49axGWv9cwAXa64wew(fileName);
		T4_ = (NIM_BOOL)0;
		T4_ = contains_jPdUhZfr9a8sH2V3ZBDljzwseriesManager(dataToBeProecessed_aGKSlMaoiyeQEXicsP8HXw->data, dataToBeProecessed_aGKSlMaoiyeQEXicsP8HXw->Sup.len, T3_);
		if (!T4_) goto LA5_;
		nimln_(132, "seriesManager.nim");
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA5_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_timesDatInit000();
	stdlib_posixDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	stdlib_pcreDatInit000();
	stdlib_rtarraysDatInit000();
	stdlib_reDatInit000();
	seriesManagerDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_timesInit000();
	stdlib_posixInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
	stdlib_pcreInit000();
	stdlib_rtarraysInit000();
	stdlib_reInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	nimfr_("seriesManager", "seriesManager.nim")
nimRegisterGlobalMarker(TM_J0OujsCJVF855gnHg567Eg_2);
nimRegisterGlobalMarker(TM_J0OujsCJVF855gnHg567Eg_3);
nimRegisterGlobalMarker(TM_J0OujsCJVF855gnHg567Eg_9);
nimRegisterGlobalMarker(TM_J0OujsCJVF855gnHg567Eg_18);
nimRegisterGlobalMarker(TM_J0OujsCJVF855gnHg567Eg_21);
nimRegisterGlobalMarker(TM_J0OujsCJVF855gnHg567Eg_23);
nimRegisterGlobalMarker(TM_J0OujsCJVF855gnHg567Eg_25);
nimRegisterGlobalMarker(TM_J0OujsCJVF855gnHg567Eg_27);
nimRegisterGlobalMarker(TM_J0OujsCJVF855gnHg567Eg_29);
	nimln_(6, "seriesManager.nim");
	if (dataToBeProecessed_aGKSlMaoiyeQEXicsP8HXw) nimGCunrefNoCycle(dataToBeProecessed_aGKSlMaoiyeQEXicsP8HXw);
	dataToBeProecessed_aGKSlMaoiyeQEXicsP8HXw = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
	nimln_(7, "seriesManager.nim");
	genericAssign((void*)fileExtensions_K9clLC6KernbjfUsLEODX1Q, (void*)TM_J0OujsCJVF855gnHg567Eg_4, (&NTI_sMpvt1sOxOJ3LFGulnbeMQ_));
	nimln_(8, "seriesManager.nim");
	genericAssign((void*)videoEncodingFormat_dAy9cWFlcUPig52GMS3XhzA, (void*)TM_J0OujsCJVF855gnHg567Eg_10, (&NTI_DLxB9cOndPvLDyky9bY9ccM3g_));
	nimln_(9, "seriesManager.nim");
	genericAssign((void*)seriesNameFolders_ApgA9cgSfvlp9bB9b9cZhrgltg, (void*)TM_J0OujsCJVF855gnHg567Eg_19, (&NTI_nHXaesL0DJZHyVS07ARPRA_));
	nimln_(11, "seriesManager.nim");
	asgnRefNoCycle((void**) (&episodePattern1_2coGGuZQmgjPi0ltcHTQ0g), re_2TnOqvPvxix6tRYnuIeq9bw(((NimStringDesc*) &TM_J0OujsCJVF855gnHg567Eg_22), 24));
	nimln_(12, "seriesManager.nim");
	asgnRefNoCycle((void**) (&episodePattern2_h2An9ay29cIRc09cJGyK4JTBw), re_2TnOqvPvxix6tRYnuIeq9bw(((NimStringDesc*) &TM_J0OujsCJVF855gnHg567Eg_24), 24));
	nimln_(13, "seriesManager.nim");
	asgnRefNoCycle((void**) (&episodePattern3_cM7OgiY1WNSwP9avickKvFg), re_2TnOqvPvxix6tRYnuIeq9bw(((NimStringDesc*) &TM_J0OujsCJVF855gnHg567Eg_26), 24));
	nimln_(14, "seriesManager.nim");
	asgnRefNoCycle((void**) (&episodePattern4_cyw3gVguaMr6sG0K49b6ElQ), re_2TnOqvPvxix6tRYnuIeq9bw(((NimStringDesc*) &TM_J0OujsCJVF855gnHg567Eg_28), 24));
	nimln_(16, "seriesManager.nim");
	asgnRefNoCycle((void**) (&yearPattern_h2XZ0aCURHWP8N30Rxb5YQ), re_2TnOqvPvxix6tRYnuIeq9bw(((NimStringDesc*) &TM_J0OujsCJVF855gnHg567Eg_30), 24));
	nimln_(134, "seriesManager.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = getSeriesNameFromFile_Yt9cWKv49axGWv9cwAXa64wew(((NimStringDesc*) &TM_J0OujsCJVF855gnHg567Eg_44));
	T2_ = (NimStringDesc*)0;
	T2_ = nimBoolToStr(eqStrings(T1_, ((NimStringDesc*) &TM_J0OujsCJVF855gnHg567Eg_45)));
	printf("%s\012", T2_? (T2_)->data:"nil");
	fflush(stdout);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, seriesManagerDatInit000)(void) {
NTI_sMpvt1sOxOJ3LFGulnbeMQ_.size = sizeof(TY_sMpvt1sOxOJ3LFGulnbeMQ);
NTI_sMpvt1sOxOJ3LFGulnbeMQ_.kind = 16;
NTI_sMpvt1sOxOJ3LFGulnbeMQ_.base = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
NTI_sMpvt1sOxOJ3LFGulnbeMQ_.flags = 2;
NTI_DLxB9cOndPvLDyky9bY9ccM3g_.size = sizeof(TY_DLxB9cOndPvLDyky9bY9ccM3g);
NTI_DLxB9cOndPvLDyky9bY9ccM3g_.kind = 16;
NTI_DLxB9cOndPvLDyky9bY9ccM3g_.base = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
NTI_DLxB9cOndPvLDyky9bY9ccM3g_.flags = 2;
NTI_nHXaesL0DJZHyVS07ARPRA_.size = sizeof(TY_nHXaesL0DJZHyVS07ARPRA);
NTI_nHXaesL0DJZHyVS07ARPRA_.kind = 16;
NTI_nHXaesL0DJZHyVS07ARPRA_.base = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
NTI_nHXaesL0DJZHyVS07ARPRA_.flags = 2;
}

