/* Generated by Nim Compiler v0.16.1 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/almynic/Nim/lib -o /home/almynic/Desktop/NimProjects/SeriesManager/nimcache/stdlib_re.o /home/almynic/Desktop/NimProjects/SeriesManager/nimcache/stdlib_re.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef linux
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct RegexError_umh9boX2MJLOyMwHcR9cwMtQ RegexError_umh9boX2MJLOyMwHcR9cwMtQ;
typedef struct ValueError_Gi06FkNeykJn7mrqRZYrkA ValueError_Gi06FkNeykJn7mrqRZYrkA;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell_1zcF9cV8XIAtbN8h5HRUB8g Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct CellSeq_Axo1XVm9aaQueTOldv8le5w CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct GcHeap_1TRH1TZMaVZTnLNcIHuNFQ GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct GcStack_7fytPA5bBsob6See21YMRA GcStack_7fytPA5bBsob6See21YMRA;
typedef struct MemRegion_x81NhDv59b8ercDZ9bi85jyg MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct SmallChunk_tXn60W2f8h3jgAYdEmy5NQ SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct LLChunk_XsENErzHIZV9bhvyJx56wGw LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct BigChunk_Rv9c70Uhp2TytkX7eH78qEg BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct IntSet_EZObFrE3NC9bIb3YMkY9crZA IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct Trunk_W0r8S0Y3UGke6T9bIUWnnuw Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct AvlNode_IaqjtwKhxLEpvDS9bct9blEw AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct GcStat_0RwLoVBHZPfUAcLczmfQAg GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct CellSet_jG87P0AI9aZtss9ccTYBIISQ CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct PageDesc_fublkgIY4LG3mT51LU2WHg PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct Pcre_bGVj3RgRlNY6kwJpiYI9b3A Pcre_bGVj3RgRlNY6kwJpiYI9b3A;
typedef struct RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw;
typedef struct ExtraData_aRbi7557vgG4KV47nk1CWQ ExtraData_aRbi7557vgG4KV47nk1CWQ;
typedef struct RtArray_gCKWFhLtuzYY1Ki6cuwEPQ RtArray_gCKWFhLtuzYY1Ki6cuwEPQ;
typedef struct TY_9apztJSmgERYU8fZOjI4pOg TY_9apztJSmgERYU8fZOjI4pOg;
typedef struct TY_1v9bKyksXWMsm0vNwmZ4EuQ TY_1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct TY_sM4lkSb7zS6F7OVMvW9cffQ TY_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct TY_4EWZfv5iIr5c71NF3I6MwQ TY_4EWZfv5iIr5c71NF3I6MwQ;
typedef struct BaseChunk_Sdq7WpT6qAH858F5ZEdG3w BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct FreeCell_u6M5LHprqzkn9axr04yg9bGQ FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct  TNimType  {
NI size;
TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  ValueError_Gi06FkNeykJn7mrqRZYrkA  {
  Exception Sup;
};
struct  RegexError_umh9boX2MJLOyMwHcR9cwMtQ  {
  ValueError_Gi06FkNeykJn7mrqRZYrkA Sup;
};
typedef NU8 TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell_1zcF9cV8XIAtbN8h5HRUB8g  {
NI refcount;
TNimType* typ;
};
struct  GcStack_7fytPA5bBsob6See21YMRA  {
void* bottom;
};
struct  CellSeq_Axo1XVm9aaQueTOldv8le5w  {
NI len;
NI cap;
Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* TY_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef Trunk_W0r8S0Y3UGke6T9bIUWnnuw* TY_lh2A89ahMmYg9bCmpVaplLbA[256];
struct  IntSet_EZObFrE3NC9bIb3YMkY9crZA  {
TY_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef AvlNode_IaqjtwKhxLEpvDS9bct9blEw* TY_0aOLqZchNi8nWtMTi8ND8w[2];
struct  AvlNode_IaqjtwKhxLEpvDS9bct9blEw  {
TY_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct  MemRegion_x81NhDv59b8ercDZ9bi85jyg  {
NI minLargeObj;
NI maxLargeObj;
TY_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* heapLink;
IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
};
struct  GcStat_0RwLoVBHZPfUAcLczmfQAg  {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct  CellSet_jG87P0AI9aZtss9ccTYBIISQ  {
NI counter;
NI max;
PageDesc_fublkgIY4LG3mT51LU2WHg* head;
PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct  GcHeap_1TRH1TZMaVZTnLNcIHuNFQ  {
GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
typedef N_CDECL_PTR(Pcre_bGVj3RgRlNY6kwJpiYI9b3A*, TY_OMNNRjh8IIE9bAc9btZcg0NA) (NCSTRING pattern, int options, NCSTRING* errptr, int* erroffset, void* tableptr);
typedef N_CDECL_PTR(void, TY_5cp59bim9aJ4WupX5aVaD1Sg) (NCSTRING stringptr);
struct  RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw  {
Pcre_bGVj3RgRlNY6kwJpiYI9b3A* h;
ExtraData_aRbi7557vgG4KV47nk1CWQ* e;
};
typedef NU8 RegexFlag_gA189bEOtGhLt2cCHGW4ywg_Set;
typedef NU8 RegexFlag_gA189bEOtGhLt2cCHGW4ywg;
typedef N_CDECL_PTR(int, TY_KqPl2ltkjnSoyb04zAVCAQ) (int what, void* where);
typedef N_CDECL_PTR(ExtraData_aRbi7557vgG4KV47nk1CWQ*, TY_qU2uMIyWirSwn1Nd4hJjDw) (Pcre_bGVj3RgRlNY6kwJpiYI9b3A* code, int options, NCSTRING* errptr);
typedef int TY_hlIpJIfs8ECqDyETXoMStg[10];
struct  RtArray_gCKWFhLtuzYY1Ki6cuwEPQ  {
NI L;
TY_9apztJSmgERYU8fZOjI4pOg* spart;
TY_hlIpJIfs8ECqDyETXoMStg apart;
};
typedef N_CDECL_PTR(int, TY_y4Iy0gL1MDnSGVt43uUAgQ) (Pcre_bGVj3RgRlNY6kwJpiYI9b3A* code, ExtraData_aRbi7557vgG4KV47nk1CWQ* extra, NCSTRING subject, int length, int startoffset, int options, int* ovector, int ovecsize);
struct TY_1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
typedef NimStringDesc* TY_Qdg3zgcNlmwGTTeVxyC9bbw[20];
struct TY_4EWZfv5iIr5c71NF3I6MwQ {
RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* Field0;
NimStringDesc* Field1;
};
struct  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w  {
NI prevSize;
NI size;
NI origSize;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* heapLink;
};
struct  SmallChunk_tXn60W2f8h3jgAYdEmy5NQ  {
  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct  LLChunk_XsENErzHIZV9bhvyJx56wGw  {
NI size;
NI acc;
LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct  BigChunk_Rv9c70Uhp2TytkX7eH78qEg  {
  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI TY_9a8QARi5WsUggNU9bom7kzTQ[8];
struct  Trunk_W0r8S0Y3UGke6T9bIUWnnuw  {
Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct  PageDesc_fublkgIY4LG3mT51LU2WHg  {
PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct  Pcre_bGVj3RgRlNY6kwJpiYI9b3A  {
char dummy;
};
struct  ExtraData_aRbi7557vgG4KV47nk1CWQ  {
long flags;
void* study_data;
long match_limit;
void* callout_data;
void* tables;
long match_limit_recursion;
void* mark;
void* executable_jit;
};
struct  FreeCell_u6M5LHprqzkn9axr04yg9bGQ  {
FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct TY_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct TY_9apztJSmgERYU8fZOjI4pOg {
  TGenericSeq Sup;
  int data[SEQ_DECL_SIZE];
};
N_NOINLINE(void, raiseInvalidRegex_uBem1bks9b5wqsVked8xr0Q)(NimStringDesc* msg) __attribute__((noreturn));
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_TY_TzXIVAyhJcYnc0aWQVu3gg)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(CellSeq_Axo1XVm9aaQueTOldv8le5w* s, Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(Pcre_bGVj3RgRlNY6kwJpiYI9b3A*, rawCompile_haWBfS5PJ5KixJQ9ccC8t5Q)(NimStringDesc* pattern, int flags);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, nsuRepeatChar)(NIM_CHAR c, NI count);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(void, finalizeRegEx_00ANangMP3AvVFMngMDJRQ)(RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* x);
N_NIMCALL(RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw*, re_2TnOqvPvxix6tRYnuIeq9bw)(NimStringDesc* s, RegexFlag_gA189bEOtGhLt2cCHGW4ywg_Set flags);
static N_NIMCALL(void, Marker_TY_dkhOdInu11QXB2HnNpgmJQ)(void* p, NI op);
static N_INLINE(NimStringDesc*, bufSubstr_dSUfaqo9a4bBy4fZeRIsArQre)(NCSTRING b, NI sPos, NI ePos);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
N_NIMCALL(void, initRtArray_BEO9bqjB0QqvrdxOQ9azwanw)(NI len, RtArray_gCKWFhLtuzYY1Ki6cuwEPQ* Result);
N_NIMCALL(int*, getRawData_WlBKlrdfyc2QaytsiK0Dyw)(RtArray_gCKWFhLtuzYY1Ki6cuwEPQ* x);
N_NIMCALL(int, matchOrFind_ZplXC9aaMp1xKMHlJu8mEEg)(NCSTRING buf, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NimStringDesc** matches, NI matchesLen_0, int start, int bufSize, int flags);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(TY_1v9bKyksXWMsm0vNwmZ4EuQ, findBounds_b9apHEMoUrbMb9bcE3q9cODKg)(NCSTRING buf, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NimStringDesc** matches, NI matchesLen_0, NI start, NI bufSize);
static N_INLINE(TY_1v9bKyksXWMsm0vNwmZ4EuQ, findBounds_xkVWeOO9a9clG6d1oOg4rtDQre)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NimStringDesc** matches, NI matchesLen_0, NI start);
N_NIMCALL(TY_1v9bKyksXWMsm0vNwmZ4EuQ, findBounds_9aR9baPBmSxN4311HBLVmqhw)(NCSTRING buf, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, TY_1v9bKyksXWMsm0vNwmZ4EuQ* matches, NI matchesLen_0, NI start, NI bufSize);
static N_INLINE(TY_1v9bKyksXWMsm0vNwmZ4EuQ, findBounds_fMe4j5jteHqQRA0Ah5lYggre)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, TY_1v9bKyksXWMsm0vNwmZ4EuQ* matches, NI matchesLen_0, NI start);
N_NIMCALL(TY_1v9bKyksXWMsm0vNwmZ4EuQ, findBounds_NDaXCMh0WoxtoBJvmimFsA)(NCSTRING buf, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start, NI bufSize);
static N_INLINE(TY_1v9bKyksXWMsm0vNwmZ4EuQ, findBounds_ueq9aDwcvl1aqUpmtCplmrAre)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start);
N_NIMCALL(int, matchOrFind_lYP9aKTHndN56JtpfLZGvIg)(NCSTRING buf, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start, NI bufSize, int flags);
static N_INLINE(NI, matchLen_SG5PU3DKAXRWI7vCeKQOCQre)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NimStringDesc** matches, NI matchesLen_0, NI start);
static N_INLINE(NI, matchLen_Dok1EtENwM9ayJsqxZJOlTQre)(NCSTRING buf, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NimStringDesc** matches, NI matchesLen_0, NI start, NI bufSize);
static N_INLINE(NI, matchLen_Qgadm9adOmbpTJaQImyB4SQre)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start);
static N_INLINE(NI, matchLen_8tsep9b9cDFrTyTR0WU8CZogre)(NCSTRING buf, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start, NI bufSize);
static N_INLINE(NIM_BOOL, match_y7rJUCS8uxf8NYoExwh5sAre)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start);
static N_INLINE(NIM_BOOL, match_emOFZQnjweIKzqVZYIeg7Are)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NimStringDesc** matches, NI matchesLen_0, NI start);
static N_INLINE(NIM_BOOL, match_c0dNj9aR5i2t09cpqqOweb9aAre)(NCSTRING buf, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NimStringDesc** matches, NI matchesLen_0, NI start, NI bufSize);
N_NIMCALL(NI, find_h9b0CsNbjKuk9c6lgvmZ9bbWQ)(NCSTRING buf, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NimStringDesc** matches, NI matchesLen_0, NI start, NI bufSize);
static N_INLINE(NI, find_SG5PU3DKAXRWI7vCeKQOCQ_2re)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NimStringDesc** matches, NI matchesLen_0, NI start);
N_NIMCALL(NI, find_gO27BvVdKY9cNNmXqtaKGdQ)(NCSTRING buf, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start, NI bufSize);
static N_INLINE(NI, find_Qgadm9adOmbpTJaQImyB4SQ_2re)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start);
static N_INLINE(TY_sM4lkSb7zS6F7OVMvW9cffQ*, findAll_YDlimI2Xg3VrhZS25a4nbgre)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
static N_INLINE(NIM_BOOL, contains_y7rJUCS8uxf8NYoExwh5sA_2re)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start);
static N_INLINE(NIM_BOOL, contains_emOFZQnjweIKzqVZYIeg7A_2re)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NimStringDesc** matches, NI matchesLen_0, NI start);
static N_INLINE(NIM_BOOL, startsWith_XM0LnZUMEz0RIyZMmxUzxwre)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* prefix);
static N_INLINE(NIM_BOOL, endsWith_iZO9aP0BzM3ahhjlSmmVLYwre)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* suffix);
N_NIMCALL(NimStringDesc*, replace_XTFad3adT9ckW2xJiSYMhMw)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* sub, NimStringDesc* by);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI start);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI first);
N_NIMCALL(NimStringDesc*, replacef_XTFad3adT9ckW2xJiSYMhMw_2)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* sub, NimStringDesc* by);
N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_NIMCALL(void, nsuAddf)(NimStringDesc** s, NimStringDesc* formatstr, NimStringDesc** a, NI aLen_0);
N_NIMCALL(NimStringDesc*, parallelReplace_DkOr4ZWhOYqa6wj44TnUAw)(NimStringDesc* s, TY_4EWZfv5iIr5c71NF3I6MwQ* subs, NI subsLen_0);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(void, transformFile_Ltcx3AnuBI8VhKrGLy16sg)(NimStringDesc* infile, NimStringDesc* outfile, TY_4EWZfv5iIr5c71NF3I6MwQ* subs, NI subsLen_0);
N_NIMCALL(NimStringDesc*, readFile_T9cm5LIRX2tKEH9aREBZ8A0w)(NimStringDesc* filename);
N_NIMCALL(void, writeFile_c1B29b0ZdDRPHc27YaKqwaA)(NimStringDesc* filename, NimStringDesc* content);
static N_INLINE(TY_sM4lkSb7zS6F7OVMvW9cffQ*, split_Z7ZBo8kHSBAfoa09amRR7igre)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* sep);
N_NIMCALL(NimStringDesc*, escapeRe_HIhHclJDvoNgVaSJbUAW9bA)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, nsuToHex)(NI64 x, NI len);
extern TNimType NTI_Gi06FkNeykJn7mrqRZYrkA_;
TNimType NTI_umh9boX2MJLOyMwHcR9cwMtQ_;
TNimType NTI_TzXIVAyhJcYnc0aWQVu3gg_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TY_OMNNRjh8IIE9bAc9btZcg0NA Dl_173601_;
extern TY_5cp59bim9aJ4WupX5aVaD1Sg Dl_173691_;
TNimType NTI_jxMAPyr9aBYX9b0g7iZ2E8zw_;
extern TNimType NTI_WH9aVfHDhtZbU6Y5QgauqZQ_;
extern TNimType NTI_z1uZWlkSdiDfd9ahW9a6Ibug_;
TNimType NTI_dkhOdInu11QXB2HnNpgmJQ_;
extern TY_KqPl2ltkjnSoyb04zAVCAQ Dl_173623_;
extern TY_qU2uMIyWirSwn1Nd4hJjDw Dl_173750_;
extern TY_y4Iy0gL1MDnSGVt43uUAgQ Dl_173663_;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
STRING_LITERAL(TM_EFUBs0zJOEvQ2SEKsixA2w_2, "\012", 1);
STRING_LITERAL(TM_EFUBs0zJOEvQ2SEKsixA2w_3, "^\012", 2);
NIM_CONST TY_1v9bKyksXWMsm0vNwmZ4EuQ TM_EFUBs0zJOEvQ2SEKsixA2w_23 = {((NI) -1),
((NI) 0)}
;
STRING_LITERAL(TM_EFUBs0zJOEvQ2SEKsixA2w_62, "", 0);
STRING_LITERAL(TM_EFUBs0zJOEvQ2SEKsixA2w_65, "\012  not (result == nil) ", 23);
STRING_LITERAL(TM_EFUBs0zJOEvQ2SEKsixA2w_66, "\012  not (s == nil) ", 18);
STRING_LITERAL(TM_EFUBs0zJOEvQ2SEKsixA2w_76, "\\x", 2);
STRING_LITERAL(TM_EFUBs0zJOEvQ2SEKsixA2w_78, "len(a) == L string modified while iterating over it", 51);
static N_NIMCALL(void, Marker_TY_TzXIVAyhJcYnc0aWQVu3gg)(void* p, NI op) {
	RegexError_umh9boX2MJLOyMwHcR9cwMtQ* a;
	a = (RegexError_umh9boX2MJLOyMwHcR9cwMtQ*)p;
	nimGCvisit((void*)(*a).Sup.Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.Sup.message, op);
	nimGCvisit((void*)(*a).Sup.Sup.trace, op);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim")
	result = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(138, "gc.nim");
	result = ((Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim")
	nimln_(216, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim")
	nimln_(270, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(272, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(273, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

N_NOINLINE(void, raiseInvalidRegex_uBem1bks9b5wqsVked8xr0Q)(NimStringDesc* msg) {
	RegexError_umh9boX2MJLOyMwHcR9cwMtQ* e;
	NimStringDesc* T1_;
	nimfr_("raiseInvalidRegex", "re.nim")
	e = (RegexError_umh9boX2MJLOyMwHcR9cwMtQ*)0;
	nimln_(61, "re.nim");
	e = (RegexError_umh9boX2MJLOyMwHcR9cwMtQ*) newObj((&NTI_TzXIVAyhJcYnc0aWQVu3gg_), sizeof(RegexError_umh9boX2MJLOyMwHcR9cwMtQ));
	(*e).Sup.Sup.Sup.m_type = (&NTI_umh9boX2MJLOyMwHcR9cwMtQ_);
	nimln_(62, "re.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = (*e).Sup.Sup.message; (*e).Sup.Sup.message = copyStringRC1(msg);
	if (T1_) nimGCunrefNoCycle(T1_);
	nimln_(63, "re.nim");
	raiseException((Exception*)e, "RegexError");
	popFrame();
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(Pcre_bGVj3RgRlNY6kwJpiYI9b3A*, rawCompile_haWBfS5PJ5KixJQ9ccC8t5Q)(NimStringDesc* pattern, int flags) {
	Pcre_bGVj3RgRlNY6kwJpiYI9b3A* result;
	NCSTRING msg;
	int offset;
	nimfr_("rawCompile", "re.nim")
	result = (Pcre_bGVj3RgRlNY6kwJpiYI9b3A*)0;
	nimln_(67, "re.nim");
	msg = "";
	nimln_(68, "re.nim");
	offset = ((int) 0);
	nimln_(69, "re.nim");
	result = Dl_173601_(pattern->data, flags, (&msg), (&offset), NIM_NIL);
	nimln_(70, "re.nim");
	{
		NimStringDesc* T5_;
		NimStringDesc* T6_;
		NimStringDesc* T7_;
		if (!(result == NIM_NIL)) goto LA3_;
		nimln_(71, "re.nim");
		T5_ = (NimStringDesc*)0;
		T6_ = (NimStringDesc*)0;
		T6_ = cstrToNimstr(msg);
		nimln_(1038, "strutils.nim");
		T7_ = (NimStringDesc*)0;
		T7_ = nsuRepeatChar(32, ((NI)chckRange(offset, ((NI) 0), ((NI) IL64(9223372036854775807)))));
		T5_ = rawNewString(T6_->Sup.len + pattern->Sup.len + T7_->Sup.len + 4);
appendString(T5_, T6_);
appendString(T5_, ((NimStringDesc*) &TM_EFUBs0zJOEvQ2SEKsixA2w_2));
appendString(T5_, pattern);
appendString(T5_, ((NimStringDesc*) &TM_EFUBs0zJOEvQ2SEKsixA2w_2));
appendString(T5_, T7_);
appendString(T5_, ((NimStringDesc*) &TM_EFUBs0zJOEvQ2SEKsixA2w_3));
		raiseInvalidRegex_uBem1bks9b5wqsVked8xr0Q(T5_);
	}
	LA3_: ;
	popFrame();
	return result;
}

N_NIMCALL(void, finalizeRegEx_00ANangMP3AvVFMngMDJRQ)(RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* x) {
	nimfr_("finalizeRegEx", "re.nim")
	nimln_(77, "re.nim");
	Dl_173691_(((NCSTRING) ((*x).h)));
	nimln_(78, "re.nim");
	{
		if (!!(((*x).e == 0))) goto LA3_;
		nimln_(79, "re.nim");
		Dl_173691_(((NCSTRING) ((*x).e)));
	}
	LA3_: ;
	popFrame();
}
static N_NIMCALL(void, Marker_TY_dkhOdInu11QXB2HnNpgmJQ)(void* p, NI op) {
	RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* a;
	a = (RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw*)p;
}

N_NIMCALL(RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw*, re_2TnOqvPvxix6tRYnuIeq9bw)(NimStringDesc* s, RegexFlag_gA189bEOtGhLt2cCHGW4ywg_Set flags) {
	RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* result;
	nimfr_("re", "re.nim")
	result = (RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw*)0;
	nimln_(87, "re.nim");
	result = (RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw*) newObj((&NTI_dkhOdInu11QXB2HnNpgmJQ_), sizeof(RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw));
	nimln_(88, "re.nim");
	(*result).h = rawCompile_haWBfS5PJ5KixJQ9ccC8t5Q(s, ((int) ((flags & ~ 16))));
	nimln_(89, "re.nim");
	{
		NCSTRING msg;
		int options;
		int hasJit;
		if (!((flags &(1U<<((NU)(((RegexFlag_gA189bEOtGhLt2cCHGW4ywg) 4))&7U)))!=0)) goto LA3_;
		nimln_(90, "re.nim");
		msg = "";
		nimln_(91, "re.nim");
		options = ((int) 0);
		nimln_(92, "re.nim");
		hasJit = ((int) 0);
		nimln_(93, "re.nim");
		{
			int T7_;
			T7_ = (int)0;
			T7_ = Dl_173623_(((int) 9), ((void*) ((&hasJit))));
			if (!(T7_ == ((NI32) 0))) goto LA8_;
			nimln_(94, "re.nim");
			{
				if (!(hasJit == ((NI32) 1))) goto LA12_;
				nimln_(95, "re.nim");
				options = ((int) 1);
			}
			LA12_: ;
		}
		LA8_: ;
		nimln_(96, "re.nim");
		(*result).e = Dl_173750_((*result).h, options, (&msg));
		nimln_(97, "re.nim");
		{
			NimStringDesc* T18_;
			if (!!((msg == 0))) goto LA16_;
			T18_ = (NimStringDesc*)0;
			T18_ = cstrToNimstr(msg);
			raiseInvalidRegex_uBem1bks9b5wqsVked8xr0Q(T18_);
		}
		LA16_: ;
	}
	LA3_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NimStringDesc*, bufSubstr_dSUfaqo9a4bBy4fZeRIsArQre)(NCSTRING b, NI sPos, NI ePos) {
	NimStringDesc* result;
	NI sz;
	NI TM_EFUBs0zJOEvQ2SEKsixA2w_5;
	NI TM_EFUBs0zJOEvQ2SEKsixA2w_6;
	nimfr_("bufSubstr", "re.nim")
	result = (NimStringDesc*)0;
	nimln_(102, "re.nim");
	TM_EFUBs0zJOEvQ2SEKsixA2w_5 = subInt(ePos, sPos);
	sz = (NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_5);
	nimln_(103, "re.nim");
	TM_EFUBs0zJOEvQ2SEKsixA2w_6 = addInt(sz, ((NI) 1));
	result = mnewString(((NI)chckRange((NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_6), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(104, "re.nim");
	if ((NU)(((NI) 0)) > (NU)(result->Sup.len)) raiseIndexError();
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&result->data[((NI) 0)]))), ((void*) ((&b[sPos]))), ((NI)chckRange(sz, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(105, "re.nim");
	result = setLengthStr(result, ((NI)chckRange(sz, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
	return result;
}

N_NIMCALL(int, matchOrFind_ZplXC9aaMp1xKMHlJu8mEEg)(NCSTRING buf, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NimStringDesc** matches, NI matchesLen_0, int start, int bufSize, int flags) {
	int result;
	RtArray_gCKWFhLtuzYY1Ki6cuwEPQ rtarray;
	NI TM_EFUBs0zJOEvQ2SEKsixA2w_7;
	NI TM_EFUBs0zJOEvQ2SEKsixA2w_8;
	int* rawMatches;
	int res;
	NI TM_EFUBs0zJOEvQ2SEKsixA2w_9;
	NI TM_EFUBs0zJOEvQ2SEKsixA2w_10;
	NI TM_EFUBs0zJOEvQ2SEKsixA2w_18;
	nimfr_("matchOrFind", "re.nim")
{	result = (int)0;
	memset((void*)(&rtarray), 0, sizeof(rtarray));
	nimln_(110, "re.nim");
	TM_EFUBs0zJOEvQ2SEKsixA2w_7 = addInt(matchesLen_0, ((NI) 1));
	TM_EFUBs0zJOEvQ2SEKsixA2w_8 = mulInt((NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_7), ((NI) 3));
	chckNil((void*)(&rtarray));
	memset((void*)(&rtarray), 0, sizeof(rtarray));
	initRtArray_BEO9bqjB0QqvrdxOQ9azwanw(((NI)chckRange((NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_8), ((NI) 0), ((NI) IL64(9223372036854775807)))), (&rtarray));
	nimln_(111, "re.nim");
	rawMatches = getRawData_WlBKlrdfyc2QaytsiK0Dyw((&rtarray));
	nimln_(112, "re.nim");
	nimln_(113, "re.nim");
	TM_EFUBs0zJOEvQ2SEKsixA2w_9 = addInt(matchesLen_0, ((NI) 1));
	TM_EFUBs0zJOEvQ2SEKsixA2w_10 = mulInt(((int)chckRange((NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_9), ((int) (-2147483647 -1)), ((int) 2147483647))), ((NI32) 3));
	if (TM_EFUBs0zJOEvQ2SEKsixA2w_10 < (-2147483647 -1) || TM_EFUBs0zJOEvQ2SEKsixA2w_10 > 2147483647) raiseOverflow();
	res = Dl_173663_((*pattern).h, (*pattern).e, buf, bufSize, start, flags, ((int*) (rawMatches)), (NI32)(TM_EFUBs0zJOEvQ2SEKsixA2w_10));
	nimln_(114, "re.nim");
	{
		if (!(res < ((NI32) 0))) goto LA3_;
		result = res;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NI i;
		NI colontmp_;
		NI TM_EFUBs0zJOEvQ2SEKsixA2w_11;
		NI res_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(115, "re.nim");
		TM_EFUBs0zJOEvQ2SEKsixA2w_11 = subInt(((NI) (res)), ((NI) 1));
		colontmp_ = (NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_11);
		nimln_(1925, "system.nim");
		res_2 = ((NI) 1);
		{
			nimln_(1926, "system.nim");
			while (1) {
				int a;
				NI TM_EFUBs0zJOEvQ2SEKsixA2w_12;
				int b;
				NI TM_EFUBs0zJOEvQ2SEKsixA2w_13;
				NI TM_EFUBs0zJOEvQ2SEKsixA2w_14;
				NI TM_EFUBs0zJOEvQ2SEKsixA2w_17;
				if (!(res_2 <= colontmp_)) goto LA7;
				nimln_(1927, "system.nim");
				i = res_2;
				nimln_(116, "re.nim");
				TM_EFUBs0zJOEvQ2SEKsixA2w_12 = mulInt(i, ((NI) 2));
				a = rawMatches[((NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_12))- 0];
				nimln_(117, "re.nim");
				TM_EFUBs0zJOEvQ2SEKsixA2w_13 = mulInt(i, ((NI) 2));
				TM_EFUBs0zJOEvQ2SEKsixA2w_14 = addInt((NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_13), ((NI) 1));
				b = rawMatches[((NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_14))- 0];
				nimln_(118, "re.nim");
				{
					NI TM_EFUBs0zJOEvQ2SEKsixA2w_15;
					if (!(((NI32) 0) <= a)) goto LA10_;
					nimln_(119, "re.nim");
					TM_EFUBs0zJOEvQ2SEKsixA2w_15 = subInt(i, ((NI) 1));
					if ((NU)((NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_15)) >= (NU)(matchesLen_0)) raiseIndexError();
					unsureAsgnRef((void**) (&matches[(NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_15)]), bufSubstr_dSUfaqo9a4bBy4fZeRIsArQre(buf, ((NI) (a)), ((NI) (b))));
				}
				goto LA8_;
				LA10_: ;
				{
					NI TM_EFUBs0zJOEvQ2SEKsixA2w_16;
					nimln_(120, "re.nim");
					TM_EFUBs0zJOEvQ2SEKsixA2w_16 = subInt(i, ((NI) 1));
					if ((NU)((NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_16)) >= (NU)(matchesLen_0)) raiseIndexError();
					unsureAsgnRef((void**) (&matches[(NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_16)]), copyString(NIM_NIL));
				}
				LA8_: ;
				nimln_(1946, "system.nim");
				TM_EFUBs0zJOEvQ2SEKsixA2w_17 = addInt(res_2, ((NI) 1));
				res_2 = (NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_17);
			} LA7: ;
		}
	}
	nimln_(121, "re.nim");
	TM_EFUBs0zJOEvQ2SEKsixA2w_18 = subInt(rawMatches[(((NI) 1))- 0], rawMatches[(((NI) 0))- 0]);
	if (TM_EFUBs0zJOEvQ2SEKsixA2w_18 < (-2147483647 -1) || TM_EFUBs0zJOEvQ2SEKsixA2w_18 > 2147483647) raiseOverflow();
	result = (NI32)(TM_EFUBs0zJOEvQ2SEKsixA2w_18);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(TY_1v9bKyksXWMsm0vNwmZ4EuQ, findBounds_b9apHEMoUrbMb9bcE3q9cODKg)(NCSTRING buf, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NimStringDesc** matches, NI matchesLen_0, NI start, NI bufSize) {
	TY_1v9bKyksXWMsm0vNwmZ4EuQ result;
	RtArray_gCKWFhLtuzYY1Ki6cuwEPQ rtarray;
	NI TM_EFUBs0zJOEvQ2SEKsixA2w_19;
	NI TM_EFUBs0zJOEvQ2SEKsixA2w_20;
	int* rawMatches;
	int res;
	NI TM_EFUBs0zJOEvQ2SEKsixA2w_21;
	NI TM_EFUBs0zJOEvQ2SEKsixA2w_22;
	NI TM_EFUBs0zJOEvQ2SEKsixA2w_31;
	nimfr_("findBounds", "re.nim")
{	memset((void*)(&result), 0, sizeof(result));
	memset((void*)(&rtarray), 0, sizeof(rtarray));
	nimln_(131, "re.nim");
	TM_EFUBs0zJOEvQ2SEKsixA2w_19 = addInt(matchesLen_0, ((NI) 1));
	TM_EFUBs0zJOEvQ2SEKsixA2w_20 = mulInt((NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_19), ((NI) 3));
	chckNil((void*)(&rtarray));
	memset((void*)(&rtarray), 0, sizeof(rtarray));
	initRtArray_BEO9bqjB0QqvrdxOQ9azwanw(((NI)chckRange((NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_20), ((NI) 0), ((NI) IL64(9223372036854775807)))), (&rtarray));
	nimln_(132, "re.nim");
	rawMatches = getRawData_WlBKlrdfyc2QaytsiK0Dyw((&rtarray));
	nimln_(133, "re.nim");
	nimln_(134, "re.nim");
	TM_EFUBs0zJOEvQ2SEKsixA2w_21 = addInt(matchesLen_0, ((NI) 1));
	TM_EFUBs0zJOEvQ2SEKsixA2w_22 = mulInt(((int)chckRange((NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_21), ((int) (-2147483647 -1)), ((int) 2147483647))), ((NI32) 3));
	if (TM_EFUBs0zJOEvQ2SEKsixA2w_22 < (-2147483647 -1) || TM_EFUBs0zJOEvQ2SEKsixA2w_22 > 2147483647) raiseOverflow();
	res = Dl_173663_((*pattern).h, (*pattern).e, buf, ((int)chckRange(bufSize, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(start, ((int) (-2147483647 -1)), ((int) 2147483647))), ((NI32) 0), ((int*) (rawMatches)), (NI32)(TM_EFUBs0zJOEvQ2SEKsixA2w_22));
	nimln_(135, "re.nim");
	{
		if (!(res < ((NI32) 0))) goto LA3_;
		result = TM_EFUBs0zJOEvQ2SEKsixA2w_23;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NI i;
		NI colontmp_;
		NI TM_EFUBs0zJOEvQ2SEKsixA2w_24;
		NI res_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(136, "re.nim");
		TM_EFUBs0zJOEvQ2SEKsixA2w_24 = subInt(((NI) (res)), ((NI) 1));
		colontmp_ = (NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_24);
		nimln_(1925, "system.nim");
		res_2 = ((NI) 1);
		{
			nimln_(1926, "system.nim");
			while (1) {
				int a;
				NI TM_EFUBs0zJOEvQ2SEKsixA2w_25;
				int b;
				NI TM_EFUBs0zJOEvQ2SEKsixA2w_26;
				NI TM_EFUBs0zJOEvQ2SEKsixA2w_27;
				NI TM_EFUBs0zJOEvQ2SEKsixA2w_30;
				if (!(res_2 <= colontmp_)) goto LA7;
				nimln_(1927, "system.nim");
				i = res_2;
				nimln_(137, "re.nim");
				TM_EFUBs0zJOEvQ2SEKsixA2w_25 = mulInt(i, ((NI) 2));
				a = rawMatches[((NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_25))- 0];
				nimln_(138, "re.nim");
				TM_EFUBs0zJOEvQ2SEKsixA2w_26 = mulInt(i, ((NI) 2));
				TM_EFUBs0zJOEvQ2SEKsixA2w_27 = addInt((NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_26), ((NI) 1));
				b = rawMatches[((NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_27))- 0];
				nimln_(139, "re.nim");
				{
					NI TM_EFUBs0zJOEvQ2SEKsixA2w_28;
					if (!(((NI32) 0) <= a)) goto LA10_;
					TM_EFUBs0zJOEvQ2SEKsixA2w_28 = subInt(i, ((NI) 1));
					if ((NU)((NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_28)) >= (NU)(matchesLen_0)) raiseIndexError();
					unsureAsgnRef((void**) (&matches[(NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_28)]), bufSubstr_dSUfaqo9a4bBy4fZeRIsArQre(buf, ((NI) (a)), ((NI) (b))));
				}
				goto LA8_;
				LA10_: ;
				{
					NI TM_EFUBs0zJOEvQ2SEKsixA2w_29;
					nimln_(140, "re.nim");
					TM_EFUBs0zJOEvQ2SEKsixA2w_29 = subInt(i, ((NI) 1));
					if ((NU)((NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_29)) >= (NU)(matchesLen_0)) raiseIndexError();
					unsureAsgnRef((void**) (&matches[(NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_29)]), copyString(NIM_NIL));
				}
				LA8_: ;
				nimln_(1946, "system.nim");
				TM_EFUBs0zJOEvQ2SEKsixA2w_30 = addInt(res_2, ((NI) 1));
				res_2 = (NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_30);
			} LA7: ;
		}
	}
	nimln_(141, "re.nim");
	result.Field0 = ((NI) (rawMatches[(((NI) 0))- 0]));
	TM_EFUBs0zJOEvQ2SEKsixA2w_31 = subInt(((NI) (rawMatches[(((NI) 1))- 0])), ((NI) 1));
	result.Field1 = (NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_31);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(TY_1v9bKyksXWMsm0vNwmZ4EuQ, findBounds_xkVWeOO9a9clG6d1oOg4rtDQre)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NimStringDesc** matches, NI matchesLen_0, NI start) {
	TY_1v9bKyksXWMsm0vNwmZ4EuQ result;
	nimfr_("findBounds", "re.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(149, "re.nim");
	result = findBounds_b9apHEMoUrbMb9bcE3q9cODKg(s->data, pattern, matches, matchesLen_0, start, (s ? s->Sup.len : 0));
	popFrame();
	return result;
}

N_NIMCALL(TY_1v9bKyksXWMsm0vNwmZ4EuQ, findBounds_9aR9baPBmSxN4311HBLVmqhw)(NCSTRING buf, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, TY_1v9bKyksXWMsm0vNwmZ4EuQ* matches, NI matchesLen_0, NI start, NI bufSize) {
	TY_1v9bKyksXWMsm0vNwmZ4EuQ result;
	RtArray_gCKWFhLtuzYY1Ki6cuwEPQ rtarray;
	NI TM_EFUBs0zJOEvQ2SEKsixA2w_32;
	NI TM_EFUBs0zJOEvQ2SEKsixA2w_33;
	int* rawMatches;
	int res;
	NI TM_EFUBs0zJOEvQ2SEKsixA2w_34;
	NI TM_EFUBs0zJOEvQ2SEKsixA2w_35;
	NI TM_EFUBs0zJOEvQ2SEKsixA2w_44;
	nimfr_("findBounds", "re.nim")
{	memset((void*)(&result), 0, sizeof(result));
	memset((void*)(&rtarray), 0, sizeof(rtarray));
	nimln_(160, "re.nim");
	TM_EFUBs0zJOEvQ2SEKsixA2w_32 = addInt(matchesLen_0, ((NI) 1));
	TM_EFUBs0zJOEvQ2SEKsixA2w_33 = mulInt((NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_32), ((NI) 3));
	chckNil((void*)(&rtarray));
	memset((void*)(&rtarray), 0, sizeof(rtarray));
	initRtArray_BEO9bqjB0QqvrdxOQ9azwanw(((NI)chckRange((NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_33), ((NI) 0), ((NI) IL64(9223372036854775807)))), (&rtarray));
	nimln_(161, "re.nim");
	rawMatches = getRawData_WlBKlrdfyc2QaytsiK0Dyw((&rtarray));
	nimln_(162, "re.nim");
	nimln_(163, "re.nim");
	TM_EFUBs0zJOEvQ2SEKsixA2w_34 = addInt(matchesLen_0, ((NI) 1));
	TM_EFUBs0zJOEvQ2SEKsixA2w_35 = mulInt(((int)chckRange((NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_34), ((int) (-2147483647 -1)), ((int) 2147483647))), ((NI32) 3));
	if (TM_EFUBs0zJOEvQ2SEKsixA2w_35 < (-2147483647 -1) || TM_EFUBs0zJOEvQ2SEKsixA2w_35 > 2147483647) raiseOverflow();
	res = Dl_173663_((*pattern).h, (*pattern).e, buf, ((int)chckRange(bufSize, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(start, ((int) (-2147483647 -1)), ((int) 2147483647))), ((NI32) 0), ((int*) (rawMatches)), (NI32)(TM_EFUBs0zJOEvQ2SEKsixA2w_35));
	nimln_(164, "re.nim");
	{
		if (!(res < ((NI32) 0))) goto LA3_;
		result = TM_EFUBs0zJOEvQ2SEKsixA2w_23;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NI i;
		NI colontmp_;
		NI TM_EFUBs0zJOEvQ2SEKsixA2w_36;
		NI res_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(165, "re.nim");
		TM_EFUBs0zJOEvQ2SEKsixA2w_36 = subInt(((NI) (res)), ((NI) 1));
		colontmp_ = (NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_36);
		nimln_(1925, "system.nim");
		res_2 = ((NI) 1);
		{
			nimln_(1926, "system.nim");
			while (1) {
				int a;
				NI TM_EFUBs0zJOEvQ2SEKsixA2w_37;
				int b;
				NI TM_EFUBs0zJOEvQ2SEKsixA2w_38;
				NI TM_EFUBs0zJOEvQ2SEKsixA2w_39;
				NI TM_EFUBs0zJOEvQ2SEKsixA2w_43;
				if (!(res_2 <= colontmp_)) goto LA7;
				nimln_(1927, "system.nim");
				i = res_2;
				nimln_(166, "re.nim");
				TM_EFUBs0zJOEvQ2SEKsixA2w_37 = mulInt(i, ((NI) 2));
				a = rawMatches[((NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_37))- 0];
				nimln_(167, "re.nim");
				TM_EFUBs0zJOEvQ2SEKsixA2w_38 = mulInt(i, ((NI) 2));
				TM_EFUBs0zJOEvQ2SEKsixA2w_39 = addInt((NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_38), ((NI) 1));
				b = rawMatches[((NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_39))- 0];
				nimln_(168, "re.nim");
				{
					NI TM_EFUBs0zJOEvQ2SEKsixA2w_40;
					NI TM_EFUBs0zJOEvQ2SEKsixA2w_41;
					if (!(((NI32) 0) <= a)) goto LA10_;
					TM_EFUBs0zJOEvQ2SEKsixA2w_40 = subInt(i, ((NI) 1));
					if ((NU)((NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_40)) >= (NU)(matchesLen_0)) raiseIndexError();
					matches[(NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_40)].Field0 = ((NI) (a));
					TM_EFUBs0zJOEvQ2SEKsixA2w_41 = subInt(((NI) (b)), ((NI) 1));
					matches[(NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_40)].Field1 = (NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_41);
				}
				goto LA8_;
				LA10_: ;
				{
					NI TM_EFUBs0zJOEvQ2SEKsixA2w_42;
					nimln_(169, "re.nim");
					TM_EFUBs0zJOEvQ2SEKsixA2w_42 = subInt(i, ((NI) 1));
					if ((NU)((NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_42)) >= (NU)(matchesLen_0)) raiseIndexError();
					matches[(NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_42)] = TM_EFUBs0zJOEvQ2SEKsixA2w_23;
				}
				LA8_: ;
				nimln_(1946, "system.nim");
				TM_EFUBs0zJOEvQ2SEKsixA2w_43 = addInt(res_2, ((NI) 1));
				res_2 = (NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_43);
			} LA7: ;
		}
	}
	nimln_(170, "re.nim");
	result.Field0 = ((NI) (rawMatches[(((NI) 0))- 0]));
	TM_EFUBs0zJOEvQ2SEKsixA2w_44 = subInt(((NI) (rawMatches[(((NI) 1))- 0])), ((NI) 1));
	result.Field1 = (NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_44);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(TY_1v9bKyksXWMsm0vNwmZ4EuQ, findBounds_fMe4j5jteHqQRA0Ah5lYggre)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, TY_1v9bKyksXWMsm0vNwmZ4EuQ* matches, NI matchesLen_0, NI start) {
	TY_1v9bKyksXWMsm0vNwmZ4EuQ result;
	nimfr_("findBounds", "re.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(179, "re.nim");
	result = findBounds_9aR9baPBmSxN4311HBLVmqhw(s->data, pattern, matches, matchesLen_0, start, (s ? s->Sup.len : 0));
	popFrame();
	return result;
}

N_NIMCALL(TY_1v9bKyksXWMsm0vNwmZ4EuQ, findBounds_NDaXCMh0WoxtoBJvmimFsA)(NCSTRING buf, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start, NI bufSize) {
	TY_1v9bKyksXWMsm0vNwmZ4EuQ result;
	RtArray_gCKWFhLtuzYY1Ki6cuwEPQ rtarray;
	int* rawMatches;
	int res;
	NI TM_EFUBs0zJOEvQ2SEKsixA2w_45;
	nimfr_("findBounds", "re.nim")
{	memset((void*)(&result), 0, sizeof(result));
	memset((void*)(&rtarray), 0, sizeof(rtarray));
	nimln_(187, "re.nim");
	chckNil((void*)(&rtarray));
	memset((void*)(&rtarray), 0, sizeof(rtarray));
	initRtArray_BEO9bqjB0QqvrdxOQ9azwanw(((NI) 3), (&rtarray));
	nimln_(188, "re.nim");
	rawMatches = getRawData_WlBKlrdfyc2QaytsiK0Dyw((&rtarray));
	nimln_(189, "re.nim");
	res = Dl_173663_((*pattern).h, (*pattern).e, buf, ((int)chckRange(bufSize, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(start, ((int) (-2147483647 -1)), ((int) 2147483647))), ((NI32) 0), ((int*) (rawMatches)), ((int) 3));
	nimln_(191, "re.nim");
	{
		if (!(res < ((NI32) 0))) goto LA3_;
		result.Field0 = ((NI) (res));
		result.Field1 = ((NI) 0);
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(192, "re.nim");
	result.Field0 = ((NI) (rawMatches[(((NI) 0))- 0]));
	TM_EFUBs0zJOEvQ2SEKsixA2w_45 = subInt(rawMatches[(((NI) 1))- 0], ((NI32) 1));
	if (TM_EFUBs0zJOEvQ2SEKsixA2w_45 < (-2147483647 -1) || TM_EFUBs0zJOEvQ2SEKsixA2w_45 > 2147483647) raiseOverflow();
	result.Field1 = ((NI) ((NI32)(TM_EFUBs0zJOEvQ2SEKsixA2w_45)));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(TY_1v9bKyksXWMsm0vNwmZ4EuQ, findBounds_ueq9aDwcvl1aqUpmtCplmrAre)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start) {
	TY_1v9bKyksXWMsm0vNwmZ4EuQ result;
	nimfr_("findBounds", "re.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(205, "re.nim");
	result = findBounds_NDaXCMh0WoxtoBJvmimFsA(s->data, pattern, start, (s ? s->Sup.len : 0));
	popFrame();
	return result;
}

N_NIMCALL(int, matchOrFind_lYP9aKTHndN56JtpfLZGvIg)(NCSTRING buf, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start, NI bufSize, int flags) {
	int result;
	RtArray_gCKWFhLtuzYY1Ki6cuwEPQ rtarray;
	int* rawMatches;
	nimfr_("matchOrFind", "re.nim")
	result = (int)0;
	memset((void*)(&rtarray), 0, sizeof(rtarray));
	nimln_(209, "re.nim");
	chckNil((void*)(&rtarray));
	memset((void*)(&rtarray), 0, sizeof(rtarray));
	initRtArray_BEO9bqjB0QqvrdxOQ9azwanw(((NI) 3), (&rtarray));
	nimln_(210, "re.nim");
	rawMatches = getRawData_WlBKlrdfyc2QaytsiK0Dyw((&rtarray));
	nimln_(211, "re.nim");
	result = Dl_173663_((*pattern).h, (*pattern).e, buf, ((int)chckRange(bufSize, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(start, ((int) (-2147483647 -1)), ((int) 2147483647))), flags, ((int*) (rawMatches)), ((int) 3));
	nimln_(213, "re.nim");
	{
		NI TM_EFUBs0zJOEvQ2SEKsixA2w_46;
		if (!(((NI32) 0) <= result)) goto LA3_;
		nimln_(214, "re.nim");
		TM_EFUBs0zJOEvQ2SEKsixA2w_46 = subInt(rawMatches[(((NI) 1))- 0], rawMatches[(((NI) 0))- 0]);
		if (TM_EFUBs0zJOEvQ2SEKsixA2w_46 < (-2147483647 -1) || TM_EFUBs0zJOEvQ2SEKsixA2w_46 > 2147483647) raiseOverflow();
		result = (NI32)(TM_EFUBs0zJOEvQ2SEKsixA2w_46);
	}
	LA3_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, matchLen_SG5PU3DKAXRWI7vCeKQOCQre)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NimStringDesc** matches, NI matchesLen_0, NI start) {
	NI result;
	int T1_;
	nimfr_("matchLen", "re.nim")
	result = (NI)0;
	nimln_(221, "re.nim");
	T1_ = (int)0;
	T1_ = matchOrFind_ZplXC9aaMp1xKMHlJu8mEEg(s->data, pattern, matches, matchesLen_0, ((int)chckRange(start, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange((s ? s->Sup.len : 0), ((int) (-2147483647 -1)), ((int) 2147483647))), ((int) 16));
	result = ((NI) (T1_));
	popFrame();
	return result;
}

static N_INLINE(NI, matchLen_Dok1EtENwM9ayJsqxZJOlTQre)(NCSTRING buf, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NimStringDesc** matches, NI matchesLen_0, NI start, NI bufSize) {
	NI result;
	int T1_;
	nimfr_("matchLen", "re.nim")
{	result = (NI)0;
	nimln_(228, "re.nim");
	T1_ = (int)0;
	T1_ = matchOrFind_ZplXC9aaMp1xKMHlJu8mEEg(buf, pattern, matches, matchesLen_0, ((int)chckRange(start, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(bufSize, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int) 16));
	result = ((NI) (T1_));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, matchLen_Qgadm9adOmbpTJaQImyB4SQre)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start) {
	NI result;
	int T1_;
	nimfr_("matchLen", "re.nim")
	result = (NI)0;
	nimln_(241, "re.nim");
	T1_ = (int)0;
	T1_ = matchOrFind_lYP9aKTHndN56JtpfLZGvIg(s->data, pattern, ((NI) (((int)chckRange(start, ((int) (-2147483647 -1)), ((int) 2147483647))))), ((NI) (((int)chckRange((s ? s->Sup.len : 0), ((int) (-2147483647 -1)), ((int) 2147483647))))), ((int) 16));
	result = ((NI) (T1_));
	popFrame();
	return result;
}

static N_INLINE(NI, matchLen_8tsep9b9cDFrTyTR0WU8CZogre)(NCSTRING buf, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start, NI bufSize) {
	NI result;
	int T1_;
	nimfr_("matchLen", "re.nim")
	result = (NI)0;
	nimln_(247, "re.nim");
	T1_ = (int)0;
	T1_ = matchOrFind_lYP9aKTHndN56JtpfLZGvIg(buf, pattern, ((NI) (((int)chckRange(start, ((int) (-2147483647 -1)), ((int) 2147483647))))), bufSize, ((int) 16));
	result = ((NI) (T1_));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, match_y7rJUCS8uxf8NYoExwh5sAre)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("match", "re.nim")
	result = (NIM_BOOL)0;
	nimln_(251, "re.nim");
	nimln_(347, "system.nim");
	nimln_(251, "re.nim");
	T1_ = (NI)0;
	T1_ = matchLen_8tsep9b9cDFrTyTR0WU8CZogre(s->data, pattern, start, (s ? s->Sup.len : 0));
	result = !((T1_ == ((NI) -1)));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, match_emOFZQnjweIKzqVZYIeg7Are)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NimStringDesc** matches, NI matchesLen_0, NI start) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("match", "re.nim")
	result = (NIM_BOOL)0;
	nimln_(267, "re.nim");
	nimln_(347, "system.nim");
	nimln_(267, "re.nim");
	T1_ = (NI)0;
	T1_ = matchLen_Dok1EtENwM9ayJsqxZJOlTQre(s->data, pattern, matches, matchesLen_0, start, (s ? s->Sup.len : 0));
	result = !((T1_ == ((NI) -1)));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, match_c0dNj9aR5i2t09cpqqOweb9aAre)(NCSTRING buf, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NimStringDesc** matches, NI matchesLen_0, NI start, NI bufSize) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("match", "re.nim")
	result = (NIM_BOOL)0;
	nimln_(276, "re.nim");
	nimln_(347, "system.nim");
	nimln_(276, "re.nim");
	T1_ = (NI)0;
	T1_ = matchLen_Dok1EtENwM9ayJsqxZJOlTQre(buf, pattern, matches, matchesLen_0, start, bufSize);
	result = !((T1_ == ((NI) -1)));
	popFrame();
	return result;
}

N_NIMCALL(NI, find_h9b0CsNbjKuk9c6lgvmZ9bbWQ)(NCSTRING buf, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NimStringDesc** matches, NI matchesLen_0, NI start, NI bufSize) {
	NI result;
	RtArray_gCKWFhLtuzYY1Ki6cuwEPQ rtarray;
	NI TM_EFUBs0zJOEvQ2SEKsixA2w_47;
	NI TM_EFUBs0zJOEvQ2SEKsixA2w_48;
	int* rawMatches;
	int res;
	NI TM_EFUBs0zJOEvQ2SEKsixA2w_49;
	NI TM_EFUBs0zJOEvQ2SEKsixA2w_50;
	nimfr_("find", "re.nim")
{	result = (NI)0;
	memset((void*)(&rtarray), 0, sizeof(rtarray));
	nimln_(285, "re.nim");
	TM_EFUBs0zJOEvQ2SEKsixA2w_47 = addInt(matchesLen_0, ((NI) 1));
	TM_EFUBs0zJOEvQ2SEKsixA2w_48 = mulInt((NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_47), ((NI) 3));
	chckNil((void*)(&rtarray));
	memset((void*)(&rtarray), 0, sizeof(rtarray));
	initRtArray_BEO9bqjB0QqvrdxOQ9azwanw(((NI)chckRange((NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_48), ((NI) 0), ((NI) IL64(9223372036854775807)))), (&rtarray));
	nimln_(286, "re.nim");
	rawMatches = getRawData_WlBKlrdfyc2QaytsiK0Dyw((&rtarray));
	nimln_(287, "re.nim");
	nimln_(288, "re.nim");
	TM_EFUBs0zJOEvQ2SEKsixA2w_49 = addInt(matchesLen_0, ((NI) 1));
	TM_EFUBs0zJOEvQ2SEKsixA2w_50 = mulInt(((int)chckRange((NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_49), ((int) (-2147483647 -1)), ((int) 2147483647))), ((NI32) 3));
	if (TM_EFUBs0zJOEvQ2SEKsixA2w_50 < (-2147483647 -1) || TM_EFUBs0zJOEvQ2SEKsixA2w_50 > 2147483647) raiseOverflow();
	res = Dl_173663_((*pattern).h, (*pattern).e, buf, ((int)chckRange(bufSize, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(start, ((int) (-2147483647 -1)), ((int) 2147483647))), ((NI32) 0), ((int*) (rawMatches)), (NI32)(TM_EFUBs0zJOEvQ2SEKsixA2w_50));
	nimln_(289, "re.nim");
	{
		if (!(res < ((NI32) 0))) goto LA3_;
		result = ((NI) (res));
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NI i;
		NI colontmp_;
		NI TM_EFUBs0zJOEvQ2SEKsixA2w_51;
		NI res_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(290, "re.nim");
		TM_EFUBs0zJOEvQ2SEKsixA2w_51 = subInt(((NI) (res)), ((NI) 1));
		colontmp_ = (NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_51);
		nimln_(1925, "system.nim");
		res_2 = ((NI) 1);
		{
			nimln_(1926, "system.nim");
			while (1) {
				int a;
				NI TM_EFUBs0zJOEvQ2SEKsixA2w_52;
				int b;
				NI TM_EFUBs0zJOEvQ2SEKsixA2w_53;
				NI TM_EFUBs0zJOEvQ2SEKsixA2w_54;
				NI TM_EFUBs0zJOEvQ2SEKsixA2w_57;
				if (!(res_2 <= colontmp_)) goto LA7;
				nimln_(1927, "system.nim");
				i = res_2;
				nimln_(291, "re.nim");
				TM_EFUBs0zJOEvQ2SEKsixA2w_52 = mulInt(i, ((NI) 2));
				a = rawMatches[((NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_52))- 0];
				nimln_(292, "re.nim");
				TM_EFUBs0zJOEvQ2SEKsixA2w_53 = mulInt(i, ((NI) 2));
				TM_EFUBs0zJOEvQ2SEKsixA2w_54 = addInt((NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_53), ((NI) 1));
				b = rawMatches[((NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_54))- 0];
				nimln_(293, "re.nim");
				{
					NI TM_EFUBs0zJOEvQ2SEKsixA2w_55;
					if (!(((NI32) 0) <= a)) goto LA10_;
					TM_EFUBs0zJOEvQ2SEKsixA2w_55 = subInt(i, ((NI) 1));
					if ((NU)((NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_55)) >= (NU)(matchesLen_0)) raiseIndexError();
					unsureAsgnRef((void**) (&matches[(NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_55)]), bufSubstr_dSUfaqo9a4bBy4fZeRIsArQre(buf, ((NI) (a)), ((NI) (b))));
				}
				goto LA8_;
				LA10_: ;
				{
					NI TM_EFUBs0zJOEvQ2SEKsixA2w_56;
					nimln_(294, "re.nim");
					TM_EFUBs0zJOEvQ2SEKsixA2w_56 = subInt(i, ((NI) 1));
					if ((NU)((NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_56)) >= (NU)(matchesLen_0)) raiseIndexError();
					unsureAsgnRef((void**) (&matches[(NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_56)]), copyString(NIM_NIL));
				}
				LA8_: ;
				nimln_(1946, "system.nim");
				TM_EFUBs0zJOEvQ2SEKsixA2w_57 = addInt(res_2, ((NI) 1));
				res_2 = (NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_57);
			} LA7: ;
		}
	}
	nimln_(295, "re.nim");
	result = ((NI) (rawMatches[(((NI) 0))- 0]));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, find_SG5PU3DKAXRWI7vCeKQOCQ_2re)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NimStringDesc** matches, NI matchesLen_0, NI start) {
	NI result;
	nimfr_("find", "re.nim")
	result = (NI)0;
	nimln_(302, "re.nim");
	result = find_h9b0CsNbjKuk9c6lgvmZ9bbWQ(s->data, pattern, matches, matchesLen_0, start, (s ? s->Sup.len : 0));
	popFrame();
	return result;
}

N_NIMCALL(NI, find_gO27BvVdKY9cNNmXqtaKGdQ)(NCSTRING buf, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start, NI bufSize) {
	NI result;
	RtArray_gCKWFhLtuzYY1Ki6cuwEPQ rtarray;
	int* rawMatches;
	int res;
	nimfr_("find", "re.nim")
{	result = (NI)0;
	memset((void*)(&rtarray), 0, sizeof(rtarray));
	nimln_(309, "re.nim");
	chckNil((void*)(&rtarray));
	memset((void*)(&rtarray), 0, sizeof(rtarray));
	initRtArray_BEO9bqjB0QqvrdxOQ9azwanw(((NI) 3), (&rtarray));
	nimln_(310, "re.nim");
	rawMatches = getRawData_WlBKlrdfyc2QaytsiK0Dyw((&rtarray));
	nimln_(311, "re.nim");
	res = Dl_173663_((*pattern).h, (*pattern).e, buf, ((int)chckRange(bufSize, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(start, ((int) (-2147483647 -1)), ((int) 2147483647))), ((NI32) 0), ((int*) (rawMatches)), ((int) 3));
	nimln_(313, "re.nim");
	{
		if (!(res < ((NI32) 0))) goto LA3_;
		result = ((NI) (res));
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(314, "re.nim");
	result = ((NI) (rawMatches[(((NI) 0))- 0]));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, find_Qgadm9adOmbpTJaQImyB4SQ_2re)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start) {
	NI result;
	nimfr_("find", "re.nim")
	result = (NI)0;
	nimln_(326, "re.nim");
	result = find_gO27BvVdKY9cNNmXqtaKGdQ(s->data, pattern, start, (s ? s->Sup.len : 0));
	popFrame();
	return result;
}

static N_INLINE(TY_sM4lkSb7zS6F7OVMvW9cffQ*, findAll_YDlimI2Xg3VrhZS25a4nbgre)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start) {
	TY_sM4lkSb7zS6F7OVMvW9cffQ* result;
	nimfr_("findAll", "re.nim")
	result = (TY_sM4lkSb7zS6F7OVMvW9cffQ*)0;
	nimln_(2459, "system.nim");
	result = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) newSeq((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
	{
		NimStringDesc* x;
		NI32 i;
		RtArray_gCKWFhLtuzYY1Ki6cuwEPQ rtarray;
		int* rawMatches;
		x = (NimStringDesc*)0;
		nimln_(334, "re.nim");
		i = ((NI32)chckRange(start, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
		memset((void*)(&rtarray), 0, sizeof(rtarray));
		nimln_(335, "re.nim");
		chckNil((void*)(&rtarray));
		memset((void*)(&rtarray), 0, sizeof(rtarray));
		initRtArray_BEO9bqjB0QqvrdxOQ9azwanw(((NI) 3), (&rtarray));
		nimln_(336, "re.nim");
		rawMatches = getRawData_WlBKlrdfyc2QaytsiK0Dyw((&rtarray));
		{
			nimln_(337, "re.nim");
			while (1) {
				int res;
				int a;
				int b;
				NI TM_EFUBs0zJOEvQ2SEKsixA2w_58;
				NimStringDesc* T14_;
				nimln_(338, "re.nim");
				res = Dl_173663_((*pattern).h, (*pattern).e, s->data, ((int)chckRange((s ? s->Sup.len : 0), ((int) (-2147483647 -1)), ((int) 2147483647))), i, ((NI32) 0), ((int*) (rawMatches)), ((int) 3));
				nimln_(340, "re.nim");
				{
					if (!(res < ((NI32) 0))) goto LA6_;
					goto LA2;
				}
				LA6_: ;
				nimln_(341, "re.nim");
				a = rawMatches[(((NI) 0))- 0];
				nimln_(342, "re.nim");
				b = rawMatches[(((NI) 1))- 0];
				nimln_(343, "re.nim");
				{
					NIM_BOOL T10_;
					T10_ = (NIM_BOOL)0;
					T10_ = (a == b);
					if (!(T10_)) goto LA11_;
					T10_ = (a == i);
					LA11_: ;
					if (!T10_) goto LA12_;
					goto LA2;
				}
				LA12_: ;
				nimln_(344, "re.nim");
				TM_EFUBs0zJOEvQ2SEKsixA2w_58 = subInt(((NI) (b)), ((NI) 1));
				x = copyStrLast(s, ((NI) (a)), (NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_58));
				nimln_(2460, "system.nim");
				result = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&(result)->Sup, sizeof(NimStringDesc*));
				T14_ = (NimStringDesc*)0;
				T14_ = result->data[result->Sup.len]; result->data[result->Sup.len] = copyStringRC1(x);
				if (T14_) nimGCunrefNoCycle(T14_);
				++result->Sup.len;
				nimln_(345, "re.nim");
				i = b;
			}
		} LA2: ;
	}
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, contains_y7rJUCS8uxf8NYoExwh5sA_2re)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("contains", "re.nim")
{	result = (NIM_BOOL)0;
	nimln_(403, "re.nim");
	T1_ = (NI)0;
	T1_ = find_Qgadm9adOmbpTJaQImyB4SQ_2re(s, pattern, start);
	result = (((NI) 0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, contains_emOFZQnjweIKzqVZYIeg7A_2re)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NimStringDesc** matches, NI matchesLen_0, NI start) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("contains", "re.nim")
{	result = (NIM_BOOL)0;
	nimln_(408, "re.nim");
	T1_ = (NI)0;
	T1_ = find_SG5PU3DKAXRWI7vCeKQOCQ_2re(s, pattern, matches, matchesLen_0, start);
	result = (((NI) 0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, startsWith_XM0LnZUMEz0RIyZMmxUzxwre)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* prefix) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("startsWith", "re.nim")
	result = (NIM_BOOL)0;
	nimln_(412, "re.nim");
	T1_ = (NI)0;
	T1_ = matchLen_Qgadm9adOmbpTJaQImyB4SQre(s, prefix, ((NI) 0));
	result = (((NI) 0) <= T1_);
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, endsWith_iZO9aP0BzM3ahhjlSmmVLYwre)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* suffix) {
	NIM_BOOL result;
	nimfr_("endsWith", "re.nim")
{	result = (NIM_BOOL)0;
	{
		NI i;
		NI colontmp_;
		NI TM_EFUBs0zJOEvQ2SEKsixA2w_59;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(416, "re.nim");
		TM_EFUBs0zJOEvQ2SEKsixA2w_59 = subInt((s ? s->Sup.len : 0), ((NI) 1));
		colontmp_ = (NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_59);
		nimln_(1925, "system.nim");
		res = ((NI) 0);
		{
			nimln_(1926, "system.nim");
			while (1) {
				NI TM_EFUBs0zJOEvQ2SEKsixA2w_61;
				if (!(res <= colontmp_)) goto LA3;
				nimln_(1927, "system.nim");
				i = res;
				nimln_(417, "re.nim");
				{
					NI T6_;
					NI TM_EFUBs0zJOEvQ2SEKsixA2w_60;
					T6_ = (NI)0;
					T6_ = matchLen_Qgadm9adOmbpTJaQImyB4SQre(s, suffix, i);
					TM_EFUBs0zJOEvQ2SEKsixA2w_60 = subInt((s ? s->Sup.len : 0), i);
					if (!(T6_ == (NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_60))) goto LA7_;
					result = NIM_TRUE;
					goto BeforeRet_;
				}
				LA7_: ;
				nimln_(1946, "system.nim");
				TM_EFUBs0zJOEvQ2SEKsixA2w_61 = addInt(res, ((NI) 1));
				res = (NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_61);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, replace_XTFad3adT9ckW2xJiSYMhMw)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* sub, NimStringDesc* by) {
	NimStringDesc* result;
	NI prev;
	NimStringDesc* T8_;
	nimfr_("replace", "re.nim")
	result = (NimStringDesc*)0;
	nimln_(433, "re.nim");
	result = copyString(((NimStringDesc*) &TM_EFUBs0zJOEvQ2SEKsixA2w_62));
	nimln_(434, "re.nim");
	prev = ((NI) 0);
	{
		nimln_(435, "re.nim");
		while (1) {
			TY_1v9bKyksXWMsm0vNwmZ4EuQ match;
			NI TM_EFUBs0zJOEvQ2SEKsixA2w_63;
			NimStringDesc* T7_;
			NI TM_EFUBs0zJOEvQ2SEKsixA2w_64;
			nimln_(436, "re.nim");
			match = findBounds_ueq9aDwcvl1aqUpmtCplmrAre(s, sub, prev);
			nimln_(437, "re.nim");
			{
				if (!(match.Field0 < ((NI) 0))) goto LA5_;
				goto LA1;
			}
			LA5_: ;
			nimln_(438, "re.nim");
			TM_EFUBs0zJOEvQ2SEKsixA2w_63 = subInt(match.Field0, ((NI) 1));
			T7_ = (NimStringDesc*)0;
			T7_ = copyStrLast(s, prev, (NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_63));
			result = resizeString(result, T7_->Sup.len + 0);
appendString(result, T7_);
			nimln_(439, "re.nim");
			result = resizeString(result, by->Sup.len + 0);
appendString(result, by);
			nimln_(440, "re.nim");
			TM_EFUBs0zJOEvQ2SEKsixA2w_64 = addInt(match.Field1, ((NI) 1));
			prev = (NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_64);
		}
	} LA1: ;
	nimln_(441, "re.nim");
	T8_ = (NimStringDesc*)0;
	T8_ = copyStr(s, prev);
	result = resizeString(result, T8_->Sup.len + 0);
appendString(result, T8_);
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, replacef_XTFad3adT9ckW2xJiSYMhMw_2)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* sub, NimStringDesc* by) {
	NimStringDesc* result;
	TY_Qdg3zgcNlmwGTTeVxyC9bbw caps;
	NI prev;
	NimStringDesc* T16_;
	nimfr_("replacef", "re.nim")
	result = (NimStringDesc*)0;
	nimln_(457, "re.nim");
	result = copyString(((NimStringDesc*) &TM_EFUBs0zJOEvQ2SEKsixA2w_62));
	memset((void*)caps, 0, sizeof(caps));
	nimln_(459, "re.nim");
	prev = ((NI) 0);
	{
		nimln_(460, "re.nim");
		while (1) {
			TY_1v9bKyksXWMsm0vNwmZ4EuQ match;
			NI TM_EFUBs0zJOEvQ2SEKsixA2w_67;
			NimStringDesc* T15_;
			NI TM_EFUBs0zJOEvQ2SEKsixA2w_68;
			nimln_(461, "re.nim");
			match = findBounds_xkVWeOO9a9clG6d1oOg4rtDQre(s, sub, caps, 20, prev);
			nimln_(462, "re.nim");
			{
				if (!(match.Field0 < ((NI) 0))) goto LA5_;
				goto LA1;
			}
			LA5_: ;
			nimln_(463, "re.nim");
			{
				if (!!(!((result == NIM_NIL)))) goto LA9_;
				failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_EFUBs0zJOEvQ2SEKsixA2w_65));
			}
			LA9_: ;
			nimln_(464, "re.nim");
			{
				if (!!(!((s == NIM_NIL)))) goto LA13_;
				failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_EFUBs0zJOEvQ2SEKsixA2w_66));
			}
			LA13_: ;
			nimln_(465, "re.nim");
			TM_EFUBs0zJOEvQ2SEKsixA2w_67 = subInt(match.Field0, ((NI) 1));
			T15_ = (NimStringDesc*)0;
			T15_ = copyStrLast(s, prev, (NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_67));
			result = resizeString(result, T15_->Sup.len + 0);
appendString(result, T15_);
			nimln_(466, "re.nim");
			nsuAddf((&result), by, caps, 20);
			nimln_(467, "re.nim");
			TM_EFUBs0zJOEvQ2SEKsixA2w_68 = addInt(match.Field1, ((NI) 1));
			prev = (NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_68);
		}
	} LA1: ;
	nimln_(468, "re.nim");
	T16_ = (NimStringDesc*)0;
	T16_ = copyStr(s, prev);
	result = resizeString(result, T16_->Sup.len + 0);
appendString(result, T16_);
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, parallelReplace_DkOr4ZWhOYqa6wj44TnUAw)(NimStringDesc* s, TY_4EWZfv5iIr5c71NF3I6MwQ* subs, NI subsLen_0) {
	NimStringDesc* result;
	NI i;
	TY_Qdg3zgcNlmwGTTeVxyC9bbw caps;
	NimStringDesc* T11_;
	nimfr_("parallelReplace", "re.nim")
	result = (NimStringDesc*)0;
	nimln_(474, "re.nim");
	result = copyString(((NimStringDesc*) &TM_EFUBs0zJOEvQ2SEKsixA2w_62));
	nimln_(475, "re.nim");
	i = ((NI) 0);
	memset((void*)caps, 0, sizeof(caps));
	{
		nimln_(477, "re.nim");
		while (1) {
			if (!(i < (s ? s->Sup.len : 0))) goto LA2;
			{
				NI TM_EFUBs0zJOEvQ2SEKsixA2w_71;
				{
					NI j;
					NI colontmp_;
					NI res;
					j = (NI)0;
					colontmp_ = (NI)0;
					nimln_(479, "re.nim");
					colontmp_ = (subsLen_0-1);
					nimln_(1925, "system.nim");
					res = ((NI) 0);
					{
						nimln_(1926, "system.nim");
						while (1) {
							NI x;
							NI TM_EFUBs0zJOEvQ2SEKsixA2w_70;
							if (!(res <= colontmp_)) goto LA6;
							nimln_(1927, "system.nim");
							j = res;
							nimln_(480, "re.nim");
							if ((NU)(j) >= (NU)(subsLen_0)) raiseIndexError();
							x = matchLen_SG5PU3DKAXRWI7vCeKQOCQre(s, subs[j].Field0, caps, 20, i);
							nimln_(481, "re.nim");
							{
								NI TM_EFUBs0zJOEvQ2SEKsixA2w_69;
								if (!(((NI) 0) < x)) goto LA9_;
								nimln_(482, "re.nim");
								if ((NU)(j) >= (NU)(subsLen_0)) raiseIndexError();
								nsuAddf((&result), subs[j].Field1, caps, 20);
								nimln_(483, "re.nim");
								TM_EFUBs0zJOEvQ2SEKsixA2w_69 = addInt(i, x);
								i = (NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_69);
								nimln_(484, "re.nim");
								goto LA3;
							}
							LA9_: ;
							nimln_(1946, "system.nim");
							TM_EFUBs0zJOEvQ2SEKsixA2w_70 = addInt(res, ((NI) 1));
							res = (NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_70);
						} LA6: ;
					}
				}
				nimln_(485, "re.nim");
				if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
				result = addChar(result, s->data[i]);
				nimln_(486, "re.nim");
				TM_EFUBs0zJOEvQ2SEKsixA2w_71 = addInt(i, ((NI) 1));
				i = (NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_71);
			} LA3: ;
		} LA2: ;
	}
	nimln_(488, "re.nim");
	T11_ = (NimStringDesc*)0;
	T11_ = copyStr(s, i);
	result = resizeString(result, T11_->Sup.len + 0);
appendString(result, T11_);
	popFrame();
	return result;
}

N_NIMCALL(void, transformFile_Ltcx3AnuBI8VhKrGLy16sg)(NimStringDesc* infile, NimStringDesc* outfile, TY_4EWZfv5iIr5c71NF3I6MwQ* subs, NI subsLen_0) {
	NimStringDesc* x;
	NimStringDesc* T1_;
	nimfr_("transformFile", "re.nim")
	nimln_(495, "re.nim");
	x = readFile_T9cm5LIRX2tKEH9aREBZ8A0w(infile);
	nimln_(496, "re.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = parallelReplace_DkOr4ZWhOYqa6wj44TnUAw(x, subs, subsLen_0);
	writeFile_c1B29b0ZdDRPHc27YaKqwaA(outfile, T1_);
	popFrame();
}

static N_INLINE(TY_sM4lkSb7zS6F7OVMvW9cffQ*, split_Z7ZBo8kHSBAfoa09amRR7igre)(NimStringDesc* s, RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* sep) {
	TY_sM4lkSb7zS6F7OVMvW9cffQ* result;
	nimfr_("split", "re.nim")
	result = (TY_sM4lkSb7zS6F7OVMvW9cffQ*)0;
	nimln_(2459, "system.nim");
	result = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) newSeq((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
	{
		NimStringDesc* x;
		NI first;
		NI last;
		x = (NimStringDesc*)0;
		nimln_(521, "re.nim");
		first = ((NI) -1);
		nimln_(522, "re.nim");
		last = ((NI) -1);
		{
			nimln_(523, "re.nim");
			while (1) {
				NI x_2;
				if (!(last < (s ? s->Sup.len : 0))) goto LA3;
				nimln_(524, "re.nim");
				x_2 = matchLen_Qgadm9adOmbpTJaQImyB4SQre(s, sep, last);
				nimln_(525, "re.nim");
				{
					NI TM_EFUBs0zJOEvQ2SEKsixA2w_72;
					if (!(((NI) 0) < x_2)) goto LA6_;
					TM_EFUBs0zJOEvQ2SEKsixA2w_72 = addInt(last, x_2);
					last = (NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_72);
				}
				LA6_: ;
				nimln_(526, "re.nim");
				first = last;
				nimln_(527, "re.nim");
				{
					NI TM_EFUBs0zJOEvQ2SEKsixA2w_73;
					if (!(x_2 == ((NI) 0))) goto LA10_;
					TM_EFUBs0zJOEvQ2SEKsixA2w_73 = addInt(last, ((NI) 1));
					last = (NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_73);
				}
				LA10_: ;
				{
					nimln_(528, "re.nim");
					while (1) {
						NI TM_EFUBs0zJOEvQ2SEKsixA2w_74;
						if (!(last < (s ? s->Sup.len : 0))) goto LA13;
						nimln_(529, "re.nim");
						x_2 = matchLen_Qgadm9adOmbpTJaQImyB4SQre(s, sep, last);
						nimln_(530, "re.nim");
						{
							if (!(((NI) 0) <= x_2)) goto LA16_;
							goto LA12;
						}
						LA16_: ;
						nimln_(531, "re.nim");
						TM_EFUBs0zJOEvQ2SEKsixA2w_74 = addInt(last, ((NI) 1));
						last = (NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_74);
					} LA13: ;
				} LA12: ;
				nimln_(532, "re.nim");
				{
					NI TM_EFUBs0zJOEvQ2SEKsixA2w_75;
					NimStringDesc* T22_;
					if (!(first <= last)) goto LA20_;
					nimln_(533, "re.nim");
					TM_EFUBs0zJOEvQ2SEKsixA2w_75 = subInt(last, ((NI) 1));
					x = copyStrLast(s, first, (NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_75));
					nimln_(2460, "system.nim");
					result = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&(result)->Sup, sizeof(NimStringDesc*));
					T22_ = (NimStringDesc*)0;
					T22_ = result->data[result->Sup.len]; result->data[result->Sup.len] = copyStringRC1(x);
					if (T22_) nimGCunrefNoCycle(T22_);
					++result->Sup.len;
				}
				LA20_: ;
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, escapeRe_HIhHclJDvoNgVaSJbUAW9bA)(NimStringDesc* s) {
	NimStringDesc* result;
	nimfr_("escapeRe", "re.nim")
	result = (NimStringDesc*)0;
	nimln_(544, "re.nim");
	result = copyString(((NimStringDesc*) &TM_EFUBs0zJOEvQ2SEKsixA2w_62));
	{
		NIM_CHAR c;
		NI i;
		NI L;
		c = (NIM_CHAR)0;
		nimln_(3562, "system.nim");
		i = ((NI) 0);
		nimln_(3563, "system.nim");
		L = (s ? s->Sup.len : 0);
		{
			nimln_(3564, "system.nim");
			while (1) {
				NI TM_EFUBs0zJOEvQ2SEKsixA2w_77;
				if (!(i < L)) goto LA3;
				nimln_(3565, "system.nim");
				if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
				c = s->data[i];
				nimln_(546, "re.nim");
				switch (((NU8)(c))) {
				case 97 ... 122:
				case 65 ... 90:
				case 48 ... 57:
				case 95:
				{
					nimln_(548, "re.nim");
					result = addChar(result, c);
				}
				break;
				default:
				{
					NimStringDesc* T6_;
					nimln_(550, "re.nim");
					result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM_EFUBs0zJOEvQ2SEKsixA2w_76));
					nimln_(551, "re.nim");
					T6_ = (NimStringDesc*)0;
					T6_ = nsuToHex(((NI64) (((NU8)(c)))), ((NI) 2));
					result = resizeString(result, T6_->Sup.len + 0);
appendString(result, T6_);
				}
				break;
				}
				nimln_(3566, "system.nim");
				TM_EFUBs0zJOEvQ2SEKsixA2w_77 = addInt(i, ((NI) 1));
				i = (NI)(TM_EFUBs0zJOEvQ2SEKsixA2w_77);
				nimln_(3567, "system.nim");
				{
					if (!!(((s ? s->Sup.len : 0) == L))) goto LA9_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_EFUBs0zJOEvQ2SEKsixA2w_78));
				}
				LA9_: ;
			} LA3: ;
		}
	}
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_reInit000)(void) {
	nimfr_("re", "re.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_reDatInit000)(void) {
static TNimNode* TM_EFUBs0zJOEvQ2SEKsixA2w_4[2];
static TNimNode TM_EFUBs0zJOEvQ2SEKsixA2w_0[4];
NTI_umh9boX2MJLOyMwHcR9cwMtQ_.size = sizeof(RegexError_umh9boX2MJLOyMwHcR9cwMtQ);
NTI_umh9boX2MJLOyMwHcR9cwMtQ_.kind = 17;
NTI_umh9boX2MJLOyMwHcR9cwMtQ_.base = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
TM_EFUBs0zJOEvQ2SEKsixA2w_0[0].len = 0; TM_EFUBs0zJOEvQ2SEKsixA2w_0[0].kind = 2;
NTI_umh9boX2MJLOyMwHcR9cwMtQ_.node = &TM_EFUBs0zJOEvQ2SEKsixA2w_0[0];
NTI_TzXIVAyhJcYnc0aWQVu3gg_.size = sizeof(RegexError_umh9boX2MJLOyMwHcR9cwMtQ*);
NTI_TzXIVAyhJcYnc0aWQVu3gg_.kind = 22;
NTI_TzXIVAyhJcYnc0aWQVu3gg_.base = (&NTI_umh9boX2MJLOyMwHcR9cwMtQ_);
NTI_TzXIVAyhJcYnc0aWQVu3gg_.marker = Marker_TY_TzXIVAyhJcYnc0aWQVu3gg;
NTI_jxMAPyr9aBYX9b0g7iZ2E8zw_.size = sizeof(RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw);
NTI_jxMAPyr9aBYX9b0g7iZ2E8zw_.kind = 18;
NTI_jxMAPyr9aBYX9b0g7iZ2E8zw_.base = 0;
NTI_jxMAPyr9aBYX9b0g7iZ2E8zw_.flags = 3;
TM_EFUBs0zJOEvQ2SEKsixA2w_4[0] = &TM_EFUBs0zJOEvQ2SEKsixA2w_0[2];
TM_EFUBs0zJOEvQ2SEKsixA2w_0[2].kind = 1;
TM_EFUBs0zJOEvQ2SEKsixA2w_0[2].offset = offsetof(RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw, h);
TM_EFUBs0zJOEvQ2SEKsixA2w_0[2].typ = (&NTI_WH9aVfHDhtZbU6Y5QgauqZQ_);
TM_EFUBs0zJOEvQ2SEKsixA2w_0[2].name = "h";
TM_EFUBs0zJOEvQ2SEKsixA2w_4[1] = &TM_EFUBs0zJOEvQ2SEKsixA2w_0[3];
TM_EFUBs0zJOEvQ2SEKsixA2w_0[3].kind = 1;
TM_EFUBs0zJOEvQ2SEKsixA2w_0[3].offset = offsetof(RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw, e);
TM_EFUBs0zJOEvQ2SEKsixA2w_0[3].typ = (&NTI_z1uZWlkSdiDfd9ahW9a6Ibug_);
TM_EFUBs0zJOEvQ2SEKsixA2w_0[3].name = "e";
TM_EFUBs0zJOEvQ2SEKsixA2w_0[1].len = 2; TM_EFUBs0zJOEvQ2SEKsixA2w_0[1].kind = 2; TM_EFUBs0zJOEvQ2SEKsixA2w_0[1].sons = &TM_EFUBs0zJOEvQ2SEKsixA2w_4[0];
NTI_jxMAPyr9aBYX9b0g7iZ2E8zw_.node = &TM_EFUBs0zJOEvQ2SEKsixA2w_0[1];
NTI_dkhOdInu11QXB2HnNpgmJQ_.size = sizeof(RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw*);
NTI_dkhOdInu11QXB2HnNpgmJQ_.kind = 22;
NTI_dkhOdInu11QXB2HnNpgmJQ_.base = (&NTI_jxMAPyr9aBYX9b0g7iZ2E8zw_);
NTI_dkhOdInu11QXB2HnNpgmJQ_.flags = 2;
NTI_dkhOdInu11QXB2HnNpgmJQ_.marker = Marker_TY_dkhOdInu11QXB2HnNpgmJQ;
(&NTI_dkhOdInu11QXB2HnNpgmJQ_)->finalizer = (void*)finalizeRegEx_00ANangMP3AvVFMngMDJRQ;
}

